// Code generated by MockGen. DO NOT EDIT.
// Source: workspace.go
//
// Generated by this command:
//
//	mockgen -destination=./workspacetest/workspace_gomock.go -package workspacetest -source workspace.go
//

// Package workspacetest is a generated GoMock package.
package workspacetest

import (
	context "context"
	fs "io/fs"
	reflect "reflect"
	syscall "syscall"
	time "time"

	schemeapi "github.com/unstablebuild/rune-go-sdk/api/schemeapi"
	workspaceapi "github.com/unstablebuild/rune-go-sdk/api/workspaceapi"
	gomock "go.uber.org/mock/gomock"
	cell "unstable.build/rune/internal/cell"
	workspace "unstable.build/rune/internal/workspace"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// Chroot mocks base method.
func (m *MockWorkspace) Chroot(path string) (schemeapi.Scheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chroot", path)
	ret0, _ := ret[0].(schemeapi.Scheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chroot indicates an expected call of Chroot.
func (mr *MockWorkspaceMockRecorder) Chroot(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chroot", reflect.TypeOf((*MockWorkspace)(nil).Chroot), path)
}

// Close mocks base method.
func (m *MockWorkspace) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWorkspaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkspace)(nil).Close))
}

// Create mocks base method.
func (m *MockWorkspace) Create(filename string) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", filename)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkspaceMockRecorder) Create(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkspace)(nil).Create), filename)
}

// InstallDataDir mocks base method.
func (m *MockWorkspace) InstallDataDir(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallDataDir", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallDataDir indicates an expected call of InstallDataDir.
func (mr *MockWorkspaceMockRecorder) InstallDataDir(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallDataDir", reflect.TypeOf((*MockWorkspace)(nil).InstallDataDir), ctx)
}

// Join mocks base method.
func (m *MockWorkspace) Join(elem ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range elem {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockWorkspaceMockRecorder) Join(elem ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockWorkspace)(nil).Join), elem...)
}

// Load mocks base method.
func (m *MockWorkspace) Load(file workspaceapi.URI, buf *cell.Buffer, swapDir workspaceapi.URI, readOnly bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", file, buf, swapDir, readOnly)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockWorkspaceMockRecorder) Load(file, buf, swapDir, readOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockWorkspace)(nil).Load), file, buf, swapDir, readOnly)
}

// Lstat mocks base method.
func (m *MockWorkspace) Lstat(filename string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", filename)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockWorkspaceMockRecorder) Lstat(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockWorkspace)(nil).Lstat), filename)
}

// MkdirAll mocks base method.
func (m *MockWorkspace) MkdirAll(filename string, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", filename, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockWorkspaceMockRecorder) MkdirAll(filename, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockWorkspace)(nil).MkdirAll), filename, perm)
}

// NewFile mocks base method.
func (m *MockWorkspace) NewFile(fd uintptr, name string) workspaceapi.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFile", fd, name)
	ret0, _ := ret[0].(workspaceapi.File)
	return ret0
}

// NewFile indicates an expected call of NewFile.
func (mr *MockWorkspaceMockRecorder) NewFile(fd, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFile", reflect.TypeOf((*MockWorkspace)(nil).NewFile), fd, name)
}

// NewPty mocks base method.
func (m *MockWorkspace) NewPty(arg0 context.Context) (workspaceapi.Pty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPty", arg0)
	ret0, _ := ret[0].(workspaceapi.Pty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPty indicates an expected call of NewPty.
func (mr *MockWorkspaceMockRecorder) NewPty(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPty", reflect.TypeOf((*MockWorkspace)(nil).NewPty), arg0)
}

// Open mocks base method.
func (m *MockWorkspace) Open(filename string) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", filename)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockWorkspaceMockRecorder) Open(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockWorkspace)(nil).Open), filename)
}

// OpenFile mocks base method.
func (m *MockWorkspace) OpenFile(filename string, flag int, perm fs.FileMode) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", filename, flag, perm)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockWorkspaceMockRecorder) OpenFile(filename, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockWorkspace)(nil).OpenFile), filename, flag, perm)
}

// ReadDir mocks base method.
func (m *MockWorkspace) ReadDir(path string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", path)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockWorkspaceMockRecorder) ReadDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockWorkspace)(nil).ReadDir), path)
}

// Readlink mocks base method.
func (m *MockWorkspace) Readlink(link string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readlink", link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readlink indicates an expected call of Readlink.
func (mr *MockWorkspaceMockRecorder) Readlink(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readlink", reflect.TypeOf((*MockWorkspace)(nil).Readlink), link)
}

// Recover mocks base method.
func (m *MockWorkspace) Recover(file, swapFilePath workspaceapi.URI, buf *cell.Buffer, force bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", file, swapFilePath, buf, force)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recover indicates an expected call of Recover.
func (mr *MockWorkspaceMockRecorder) Recover(file, swapFilePath, buf, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockWorkspace)(nil).Recover), file, swapFilePath, buf, force)
}

// Remove mocks base method.
func (m *MockWorkspace) Remove(file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWorkspaceMockRecorder) Remove(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWorkspace)(nil).Remove), file)
}

// Rename mocks base method.
func (m *MockWorkspace) Rename(oldpath, newpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldpath, newpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockWorkspaceMockRecorder) Rename(oldpath, newpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockWorkspace)(nil).Rename), oldpath, newpath)
}

// Root mocks base method.
func (m *MockWorkspace) Root() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Root")
	ret0, _ := ret[0].(string)
	return ret0
}

// Root indicates an expected call of Root.
func (mr *MockWorkspaceMockRecorder) Root() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Root", reflect.TypeOf((*MockWorkspace)(nil).Root))
}

// SetPtySize mocks base method.
func (m *MockWorkspace) SetPtySize(p workspaceapi.Pty, size workspaceapi.PtySize) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPtySize", p, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPtySize indicates an expected call of SetPtySize.
func (mr *MockWorkspaceMockRecorder) SetPtySize(p, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPtySize", reflect.TypeOf((*MockWorkspace)(nil).SetPtySize), p, size)
}

// Signal mocks base method.
func (m *MockWorkspace) Signal(arg0 workspaceapi.Pid, arg1 syscall.Signal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockWorkspaceMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockWorkspace)(nil).Signal), arg0, arg1)
}

// StartCommand mocks base method.
func (m *MockWorkspace) StartCommand(ctx context.Context, cmd workspaceapi.Cmd) (workspaceapi.Pid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCommand", ctx, cmd)
	ret0, _ := ret[0].(workspaceapi.Pid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartCommand indicates an expected call of StartCommand.
func (mr *MockWorkspaceMockRecorder) StartCommand(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCommand", reflect.TypeOf((*MockWorkspace)(nil).StartCommand), ctx, cmd)
}

// Stat mocks base method.
func (m *MockWorkspace) Stat(filename string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", filename)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockWorkspaceMockRecorder) Stat(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockWorkspace)(nil).Stat), filename)
}

// StopWatch mocks base method.
func (m *MockWorkspace) StopWatch(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopWatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopWatch indicates an expected call of StopWatch.
func (mr *MockWorkspaceMockRecorder) StopWatch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopWatch", reflect.TypeOf((*MockWorkspace)(nil).StopWatch), arg0)
}

// Symlink mocks base method.
func (m *MockWorkspace) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockWorkspaceMockRecorder) Symlink(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockWorkspace)(nil).Symlink), oldname, newname)
}

// TempFile mocks base method.
func (m *MockWorkspace) TempFile(dir, prefix string) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempFile", dir, prefix)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempFile indicates an expected call of TempFile.
func (mr *MockWorkspaceMockRecorder) TempFile(dir, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempFile", reflect.TypeOf((*MockWorkspace)(nil).TempFile), dir, prefix)
}

// URI mocks base method.
func (m *MockWorkspace) URI(path string) (workspaceapi.URI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URI", path)
	ret0, _ := ret[0].(workspaceapi.URI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URI indicates an expected call of URI.
func (mr *MockWorkspaceMockRecorder) URI(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URI", reflect.TypeOf((*MockWorkspace)(nil).URI), path)
}

// Watch mocks base method.
func (m *MockWorkspace) Watch(path string, c chan<- schemeapi.EventInfo, events ...schemeapi.Event) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{path, c}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockWorkspaceMockRecorder) Watch(path, c any, events ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path, c}, events...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWorkspace)(nil).Watch), varargs...)
}

// MockRemoteScheme is a mock of RemoteScheme interface.
type MockRemoteScheme struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteSchemeMockRecorder
}

// MockRemoteSchemeMockRecorder is the mock recorder for MockRemoteScheme.
type MockRemoteSchemeMockRecorder struct {
	mock *MockRemoteScheme
}

// NewMockRemoteScheme creates a new mock instance.
func NewMockRemoteScheme(ctrl *gomock.Controller) *MockRemoteScheme {
	mock := &MockRemoteScheme{ctrl: ctrl}
	mock.recorder = &MockRemoteSchemeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteScheme) EXPECT() *MockRemoteSchemeMockRecorder {
	return m.recorder
}

// OnDisconnect mocks base method.
func (m *MockRemoteScheme) OnDisconnect() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDisconnect")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// OnDisconnect indicates an expected call of OnDisconnect.
func (mr *MockRemoteSchemeMockRecorder) OnDisconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDisconnect", reflect.TypeOf((*MockRemoteScheme)(nil).OnDisconnect))
}

// WaitConnected mocks base method.
func (m *MockRemoteScheme) WaitConnected(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitConnected", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitConnected indicates an expected call of WaitConnected.
func (mr *MockRemoteSchemeMockRecorder) WaitConnected(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitConnected", reflect.TypeOf((*MockRemoteScheme)(nil).WaitConnected), ctx)
}

// MockInstallDataDirProvider is a mock of InstallDataDirProvider interface.
type MockInstallDataDirProvider struct {
	ctrl     *gomock.Controller
	recorder *MockInstallDataDirProviderMockRecorder
}

// MockInstallDataDirProviderMockRecorder is the mock recorder for MockInstallDataDirProvider.
type MockInstallDataDirProviderMockRecorder struct {
	mock *MockInstallDataDirProvider
}

// NewMockInstallDataDirProvider creates a new mock instance.
func NewMockInstallDataDirProvider(ctrl *gomock.Controller) *MockInstallDataDirProvider {
	mock := &MockInstallDataDirProvider{ctrl: ctrl}
	mock.recorder = &MockInstallDataDirProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstallDataDirProvider) EXPECT() *MockInstallDataDirProviderMockRecorder {
	return m.recorder
}

// InstallDataDir mocks base method.
func (m *MockInstallDataDirProvider) InstallDataDir(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallDataDir", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallDataDir indicates an expected call of InstallDataDir.
func (mr *MockInstallDataDirProviderMockRecorder) InstallDataDir(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallDataDir", reflect.TypeOf((*MockInstallDataDirProvider)(nil).InstallDataDir), ctx)
}

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockLoader) Load(file workspaceapi.URI, buf *cell.Buffer, swapDir workspaceapi.URI, readOnly bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", file, buf, swapDir, readOnly)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockLoaderMockRecorder) Load(file, buf, swapDir, readOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockLoader)(nil).Load), file, buf, swapDir, readOnly)
}

// Recover mocks base method.
func (m *MockLoader) Recover(file, swapFilePath workspaceapi.URI, buf *cell.Buffer, force bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", file, swapFilePath, buf, force)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recover indicates an expected call of Recover.
func (mr *MockLoaderMockRecorder) Recover(file, swapFilePath, buf, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockLoader)(nil).Recover), file, swapFilePath, buf, force)
}

// Remove mocks base method.
func (m *MockLoader) Remove(file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockLoaderMockRecorder) Remove(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockLoader)(nil).Remove), file)
}

// MockSchemeManager is a mock of SchemeManager interface.
type MockSchemeManager struct {
	ctrl     *gomock.Controller
	recorder *MockSchemeManagerMockRecorder
}

// MockSchemeManagerMockRecorder is the mock recorder for MockSchemeManager.
type MockSchemeManagerMockRecorder struct {
	mock *MockSchemeManager
}

// NewMockSchemeManager creates a new mock instance.
func NewMockSchemeManager(ctrl *gomock.Controller) *MockSchemeManager {
	mock := &MockSchemeManager{ctrl: ctrl}
	mock.recorder = &MockSchemeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemeManager) EXPECT() *MockSchemeManagerMockRecorder {
	return m.recorder
}

// RegisterScheme mocks base method.
func (m *MockSchemeManager) RegisterScheme(arg0 string, arg1 schemeapi.SchemeFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterScheme", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterScheme indicates an expected call of RegisterScheme.
func (mr *MockSchemeManagerMockRecorder) RegisterScheme(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterScheme", reflect.TypeOf((*MockSchemeManager)(nil).RegisterScheme), arg0, arg1)
}

// UnregisterScheme mocks base method.
func (m *MockSchemeManager) UnregisterScheme(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterScheme", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterScheme indicates an expected call of UnregisterScheme.
func (mr *MockSchemeManagerMockRecorder) UnregisterScheme(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterScheme", reflect.TypeOf((*MockSchemeManager)(nil).UnregisterScheme), arg0)
}

// MockWorkspaceManager is a mock of WorkspaceManager interface.
type MockWorkspaceManager struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceManagerMockRecorder
}

// MockWorkspaceManagerMockRecorder is the mock recorder for MockWorkspaceManager.
type MockWorkspaceManagerMockRecorder struct {
	mock *MockWorkspaceManager
}

// NewMockWorkspaceManager creates a new mock instance.
func NewMockWorkspaceManager(ctrl *gomock.Controller) *MockWorkspaceManager {
	mock := &MockWorkspaceManager{ctrl: ctrl}
	mock.recorder = &MockWorkspaceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceManager) EXPECT() *MockWorkspaceManagerMockRecorder {
	return m.recorder
}

// AddWorkspace mocks base method.
func (m *MockWorkspaceManager) AddWorkspace(arg0 context.Context, arg1 workspaceapi.URI) (workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkspace", arg0, arg1)
	ret0, _ := ret[0].(workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddWorkspace indicates an expected call of AddWorkspace.
func (mr *MockWorkspaceManagerMockRecorder) AddWorkspace(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkspace", reflect.TypeOf((*MockWorkspaceManager)(nil).AddWorkspace), arg0, arg1)
}

// DecrementReference mocks base method.
func (m *MockWorkspaceManager) DecrementReference(arg0 workspaceapi.URI) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementReference", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementReference indicates an expected call of DecrementReference.
func (mr *MockWorkspaceManagerMockRecorder) DecrementReference(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementReference", reflect.TypeOf((*MockWorkspaceManager)(nil).DecrementReference), arg0)
}

// IncrementReference mocks base method.
func (m *MockWorkspaceManager) IncrementReference(arg0 workspaceapi.URI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementReference", arg0)
}

// IncrementReference indicates an expected call of IncrementReference.
func (mr *MockWorkspaceManagerMockRecorder) IncrementReference(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementReference", reflect.TypeOf((*MockWorkspaceManager)(nil).IncrementReference), arg0)
}

// RegisterScheme mocks base method.
func (m *MockWorkspaceManager) RegisterScheme(arg0 string, arg1 schemeapi.SchemeFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterScheme", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterScheme indicates an expected call of RegisterScheme.
func (mr *MockWorkspaceManagerMockRecorder) RegisterScheme(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterScheme", reflect.TypeOf((*MockWorkspaceManager)(nil).RegisterScheme), arg0, arg1)
}

// RemoveWorkspace mocks base method.
func (m *MockWorkspaceManager) RemoveWorkspace(arg0 workspaceapi.URI) (workspace.Workspace, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWorkspace", arg0)
	ret0, _ := ret[0].(workspace.Workspace)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// RemoveWorkspace indicates an expected call of RemoveWorkspace.
func (mr *MockWorkspaceManagerMockRecorder) RemoveWorkspace(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkspace", reflect.TypeOf((*MockWorkspaceManager)(nil).RemoveWorkspace), arg0)
}

// UnregisterScheme mocks base method.
func (m *MockWorkspaceManager) UnregisterScheme(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterScheme", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterScheme indicates an expected call of UnregisterScheme.
func (mr *MockWorkspaceManagerMockRecorder) UnregisterScheme(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterScheme", reflect.TypeOf((*MockWorkspaceManager)(nil).UnregisterScheme), arg0)
}

// Workspace mocks base method.
func (m *MockWorkspaceManager) Workspace(arg0 workspaceapi.URI) (workspace.Workspace, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Workspace", arg0)
	ret0, _ := ret[0].(workspace.Workspace)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Workspace indicates an expected call of Workspace.
func (mr *MockWorkspaceManagerMockRecorder) Workspace(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Workspace", reflect.TypeOf((*MockWorkspaceManager)(nil).Workspace), arg0)
}

// MockFlusherCloser is a mock of FlusherCloser interface.
type MockFlusherCloser struct {
	ctrl     *gomock.Controller
	recorder *MockFlusherCloserMockRecorder
}

// MockFlusherCloserMockRecorder is the mock recorder for MockFlusherCloser.
type MockFlusherCloserMockRecorder struct {
	mock *MockFlusherCloser
}

// NewMockFlusherCloser creates a new mock instance.
func NewMockFlusherCloser(ctrl *gomock.Controller) *MockFlusherCloser {
	mock := &MockFlusherCloser{ctrl: ctrl}
	mock.recorder = &MockFlusherCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlusherCloser) EXPECT() *MockFlusherCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFlusherCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFlusherCloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFlusherCloser)(nil).Close))
}

// Flush mocks base method.
func (m *MockFlusherCloser) Flush(ctx context.Context) (<-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(<-chan error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Flush indicates an expected call of Flush.
func (mr *MockFlusherCloserMockRecorder) Flush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockFlusherCloser)(nil).Flush), ctx)
}

// ForceFlush mocks base method.
func (m *MockFlusherCloser) ForceFlush(ctx context.Context) (<-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceFlush", ctx)
	ret0, _ := ret[0].(<-chan error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceFlush indicates an expected call of ForceFlush.
func (mr *MockFlusherCloserMockRecorder) ForceFlush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceFlush", reflect.TypeOf((*MockFlusherCloser)(nil).ForceFlush), ctx)
}

// LastFlush mocks base method.
func (m *MockFlusherCloser) LastFlush() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastFlush")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// LastFlush indicates an expected call of LastFlush.
func (mr *MockFlusherCloserMockRecorder) LastFlush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastFlush", reflect.TypeOf((*MockFlusherCloser)(nil).LastFlush))
}

// Reload mocks base method.
func (m *MockFlusherCloser) Reload(ctx context.Context) (<-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload", ctx)
	ret0, _ := ret[0].(<-chan error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reload indicates an expected call of Reload.
func (mr *MockFlusherCloserMockRecorder) Reload(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockFlusherCloser)(nil).Reload), ctx)
}
