// Code generated by MockGen. DO NOT EDIT.
// Source: ./browser.go
//
// Generated by this command:
//
//	mockgen -destination=./browsertest/browser_gomock.go -package browsertest -self_package unstable.build/rune/internal/browser/browserrpctest -source ./browser.go
//

// Package browsertest is a generated GoMock package.
package browsertest

import (
	reflect "reflect"

	browserapi "github.com/unstablebuild/rune-go-sdk/api/browserapi"
	workspaceapi "github.com/unstablebuild/rune-go-sdk/api/workspaceapi"
	component "github.com/unstablebuild/rune-go-sdk/component"
	term "github.com/unstablebuild/rune-go-sdk/term"
	tui "github.com/unstablebuild/rune-go-sdk/tui"
	gomock "go.uber.org/mock/gomock"
	browser "unstable.build/rune/internal/browser"
)

// MockFloating is a mock of Floating interface.
type MockFloating struct {
	ctrl     *gomock.Controller
	recorder *MockFloatingMockRecorder
}

// MockFloatingMockRecorder is the mock recorder for MockFloating.
type MockFloatingMockRecorder struct {
	mock *MockFloating
}

// NewMockFloating creates a new mock instance.
func NewMockFloating(ctrl *gomock.Controller) *MockFloating {
	mock := &MockFloating{ctrl: ctrl}
	mock.recorder = &MockFloatingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFloating) EXPECT() *MockFloatingMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFloating) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFloatingMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFloating)(nil).Close))
}

// Cursor mocks base method.
func (m *MockFloating) Cursor() (term.Coordinates, term.CursorStyle, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(term.Coordinates)
	ret1, _ := ret[1].(term.CursorStyle)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Cursor indicates an expected call of Cursor.
func (mr *MockFloatingMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockFloating)(nil).Cursor))
}

// Dimensions mocks base method.
func (m *MockFloating) Dimensions() (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dimensions")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Dimensions indicates an expected call of Dimensions.
func (mr *MockFloatingMockRecorder) Dimensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dimensions", reflect.TypeOf((*MockFloating)(nil).Dimensions))
}

// Draw mocks base method.
func (m *MockFloating) Draw(arg0 term.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Draw", arg0)
}

// Draw indicates an expected call of Draw.
func (mr *MockFloatingMockRecorder) Draw(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockFloating)(nil).Draw), arg0)
}

// Handle mocks base method.
func (m *MockFloating) Handle(arg0 term.Event) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockFloatingMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFloating)(nil).Handle), arg0)
}

// Resize mocks base method.
func (m *MockFloating) Resize(width, height int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resize", width, height)
}

// Resize indicates an expected call of Resize.
func (mr *MockFloatingMockRecorder) Resize(width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockFloating)(nil).Resize), width, height)
}

// Selection mocks base method.
func (m *MockFloating) Selection() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selection")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Selection indicates an expected call of Selection.
func (mr *MockFloatingMockRecorder) Selection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selection", reflect.TypeOf((*MockFloating)(nil).Selection))
}

// MockScrollable is a mock of Scrollable interface.
type MockScrollable struct {
	ctrl     *gomock.Controller
	recorder *MockScrollableMockRecorder
}

// MockScrollableMockRecorder is the mock recorder for MockScrollable.
type MockScrollableMockRecorder struct {
	mock *MockScrollable
}

// NewMockScrollable creates a new mock instance.
func NewMockScrollable(ctrl *gomock.Controller) *MockScrollable {
	mock := &MockScrollable{ctrl: ctrl}
	mock.recorder = &MockScrollableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrollable) EXPECT() *MockScrollableMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockScrollable) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockScrollableMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockScrollable)(nil).Close))
}

// Cursor mocks base method.
func (m *MockScrollable) Cursor() (term.Coordinates, term.CursorStyle, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(term.Coordinates)
	ret1, _ := ret[1].(term.CursorStyle)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Cursor indicates an expected call of Cursor.
func (mr *MockScrollableMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockScrollable)(nil).Cursor))
}

// Draw mocks base method.
func (m *MockScrollable) Draw(arg0 term.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Draw", arg0)
}

// Draw indicates an expected call of Draw.
func (mr *MockScrollableMockRecorder) Draw(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockScrollable)(nil).Draw), arg0)
}

// Handle mocks base method.
func (m *MockScrollable) Handle(arg0 term.Event) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockScrollableMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockScrollable)(nil).Handle), arg0)
}

// MaxSeekOffset mocks base method.
func (m *MockScrollable) MaxSeekOffset() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxSeekOffset")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxSeekOffset indicates an expected call of MaxSeekOffset.
func (mr *MockScrollableMockRecorder) MaxSeekOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxSeekOffset", reflect.TypeOf((*MockScrollable)(nil).MaxSeekOffset))
}

// Resize mocks base method.
func (m *MockScrollable) Resize(width, height int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resize", width, height)
}

// Resize indicates an expected call of Resize.
func (mr *MockScrollableMockRecorder) Resize(width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockScrollable)(nil).Resize), width, height)
}

// SeekDown mocks base method.
func (m *MockScrollable) SeekDown() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekDown")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SeekDown indicates an expected call of SeekDown.
func (mr *MockScrollableMockRecorder) SeekDown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekDown", reflect.TypeOf((*MockScrollable)(nil).SeekDown))
}

// SeekOffset mocks base method.
func (m *MockScrollable) SeekOffset() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekOffset")
	ret0, _ := ret[0].(int)
	return ret0
}

// SeekOffset indicates an expected call of SeekOffset.
func (mr *MockScrollableMockRecorder) SeekOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekOffset", reflect.TypeOf((*MockScrollable)(nil).SeekOffset))
}

// SeekUp mocks base method.
func (m *MockScrollable) SeekUp() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekUp")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SeekUp indicates an expected call of SeekUp.
func (mr *MockScrollableMockRecorder) SeekUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekUp", reflect.TypeOf((*MockScrollable)(nil).SeekUp))
}

// Selection mocks base method.
func (m *MockScrollable) Selection() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selection")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Selection indicates an expected call of Selection.
func (mr *MockScrollableMockRecorder) Selection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selection", reflect.TypeOf((*MockScrollable)(nil).Selection))
}

// MockScrollableFloating is a mock of ScrollableFloating interface.
type MockScrollableFloating struct {
	ctrl     *gomock.Controller
	recorder *MockScrollableFloatingMockRecorder
}

// MockScrollableFloatingMockRecorder is the mock recorder for MockScrollableFloating.
type MockScrollableFloatingMockRecorder struct {
	mock *MockScrollableFloating
}

// NewMockScrollableFloating creates a new mock instance.
func NewMockScrollableFloating(ctrl *gomock.Controller) *MockScrollableFloating {
	mock := &MockScrollableFloating{ctrl: ctrl}
	mock.recorder = &MockScrollableFloatingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrollableFloating) EXPECT() *MockScrollableFloatingMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockScrollableFloating) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockScrollableFloatingMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockScrollableFloating)(nil).Close))
}

// Cursor mocks base method.
func (m *MockScrollableFloating) Cursor() (term.Coordinates, term.CursorStyle, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(term.Coordinates)
	ret1, _ := ret[1].(term.CursorStyle)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Cursor indicates an expected call of Cursor.
func (mr *MockScrollableFloatingMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockScrollableFloating)(nil).Cursor))
}

// Dimensions mocks base method.
func (m *MockScrollableFloating) Dimensions() (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dimensions")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Dimensions indicates an expected call of Dimensions.
func (mr *MockScrollableFloatingMockRecorder) Dimensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dimensions", reflect.TypeOf((*MockScrollableFloating)(nil).Dimensions))
}

// Draw mocks base method.
func (m *MockScrollableFloating) Draw(arg0 term.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Draw", arg0)
}

// Draw indicates an expected call of Draw.
func (mr *MockScrollableFloatingMockRecorder) Draw(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockScrollableFloating)(nil).Draw), arg0)
}

// Handle mocks base method.
func (m *MockScrollableFloating) Handle(arg0 term.Event) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockScrollableFloatingMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockScrollableFloating)(nil).Handle), arg0)
}

// MaxSeekOffset mocks base method.
func (m *MockScrollableFloating) MaxSeekOffset() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxSeekOffset")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxSeekOffset indicates an expected call of MaxSeekOffset.
func (mr *MockScrollableFloatingMockRecorder) MaxSeekOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxSeekOffset", reflect.TypeOf((*MockScrollableFloating)(nil).MaxSeekOffset))
}

// Resize mocks base method.
func (m *MockScrollableFloating) Resize(width, height int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resize", width, height)
}

// Resize indicates an expected call of Resize.
func (mr *MockScrollableFloatingMockRecorder) Resize(width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockScrollableFloating)(nil).Resize), width, height)
}

// SeekDown mocks base method.
func (m *MockScrollableFloating) SeekDown() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekDown")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SeekDown indicates an expected call of SeekDown.
func (mr *MockScrollableFloatingMockRecorder) SeekDown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekDown", reflect.TypeOf((*MockScrollableFloating)(nil).SeekDown))
}

// SeekOffset mocks base method.
func (m *MockScrollableFloating) SeekOffset() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekOffset")
	ret0, _ := ret[0].(int)
	return ret0
}

// SeekOffset indicates an expected call of SeekOffset.
func (mr *MockScrollableFloatingMockRecorder) SeekOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekOffset", reflect.TypeOf((*MockScrollableFloating)(nil).SeekOffset))
}

// SeekUp mocks base method.
func (m *MockScrollableFloating) SeekUp() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekUp")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SeekUp indicates an expected call of SeekUp.
func (mr *MockScrollableFloatingMockRecorder) SeekUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekUp", reflect.TypeOf((*MockScrollableFloating)(nil).SeekUp))
}

// Selection mocks base method.
func (m *MockScrollableFloating) Selection() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selection")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Selection indicates an expected call of Selection.
func (mr *MockScrollableFloatingMockRecorder) Selection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selection", reflect.TypeOf((*MockScrollableFloating)(nil).Selection))
}

// MockWindow is a mock of Window interface.
type MockWindow struct {
	ctrl     *gomock.Controller
	recorder *MockWindowMockRecorder
}

// MockWindowMockRecorder is the mock recorder for MockWindow.
type MockWindowMockRecorder struct {
	mock *MockWindow
}

// NewMockWindow creates a new mock instance.
func NewMockWindow(ctrl *gomock.Controller) *MockWindow {
	mock := &MockWindow{ctrl: ctrl}
	mock.recorder = &MockWindowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindow) EXPECT() *MockWindowMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWindow) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWindowMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWindow)(nil).Close))
}

// Closed mocks base method.
func (m *MockWindow) Closed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Closed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Closed indicates an expected call of Closed.
func (mr *MockWindowMockRecorder) Closed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Closed", reflect.TypeOf((*MockWindow)(nil).Closed))
}

// Content mocks base method.
func (m *MockWindow) Content() (browserapi.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Content")
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Content indicates an expected call of Content.
func (mr *MockWindowMockRecorder) Content() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Content", reflect.TypeOf((*MockWindow)(nil).Content))
}

// Focus mocks base method.
func (m *MockWindow) Focus() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Focus")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Focus indicates an expected call of Focus.
func (mr *MockWindowMockRecorder) Focus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Focus", reflect.TypeOf((*MockWindow)(nil).Focus))
}

// Height mocks base method.
func (m *MockWindow) Height() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height.
func (mr *MockWindowMockRecorder) Height() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Height", reflect.TypeOf((*MockWindow)(nil).Height))
}

// IsFloating mocks base method.
func (m *MockWindow) IsFloating() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFloating")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFloating indicates an expected call of IsFloating.
func (mr *MockWindowMockRecorder) IsFloating() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFloating", reflect.TypeOf((*MockWindow)(nil).IsFloating))
}

// IsMinimized mocks base method.
func (m *MockWindow) IsMinimized() (component.Alignment, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMinimized")
	ret0, _ := ret[0].(component.Alignment)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsMinimized indicates an expected call of IsMinimized.
func (mr *MockWindowMockRecorder) IsMinimized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMinimized", reflect.TypeOf((*MockWindow)(nil).IsMinimized))
}

// MinimizeDown mocks base method.
func (m *MockWindow) MinimizeDown(padding int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinimizeDown", padding)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MinimizeDown indicates an expected call of MinimizeDown.
func (mr *MockWindowMockRecorder) MinimizeDown(padding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinimizeDown", reflect.TypeOf((*MockWindow)(nil).MinimizeDown), padding)
}

// MinimizeLeft mocks base method.
func (m *MockWindow) MinimizeLeft(padding int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinimizeLeft", padding)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MinimizeLeft indicates an expected call of MinimizeLeft.
func (mr *MockWindowMockRecorder) MinimizeLeft(padding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinimizeLeft", reflect.TypeOf((*MockWindow)(nil).MinimizeLeft), padding)
}

// MinimizeRight mocks base method.
func (m *MockWindow) MinimizeRight(padding int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinimizeRight", padding)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MinimizeRight indicates an expected call of MinimizeRight.
func (mr *MockWindowMockRecorder) MinimizeRight(padding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinimizeRight", reflect.TypeOf((*MockWindow)(nil).MinimizeRight), padding)
}

// MinimizeUp mocks base method.
func (m *MockWindow) MinimizeUp(padding int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinimizeUp", padding)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MinimizeUp indicates an expected call of MinimizeUp.
func (mr *MockWindowMockRecorder) MinimizeUp(padding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinimizeUp", reflect.TypeOf((*MockWindow)(nil).MinimizeUp), padding)
}

// Position mocks base method.
func (m *MockWindow) Position() term.Coordinates {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Position")
	ret0, _ := ret[0].(term.Coordinates)
	return ret0
}

// Position indicates an expected call of Position.
func (mr *MockWindowMockRecorder) Position() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Position", reflect.TypeOf((*MockWindow)(nil).Position))
}

// SetContent mocks base method.
func (m *MockWindow) SetContent(arg0 browserapi.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetContent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetContent indicates an expected call of SetContent.
func (mr *MockWindowMockRecorder) SetContent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContent", reflect.TypeOf((*MockWindow)(nil).SetContent), arg0)
}

// SetFrameAttr mocks base method.
func (m *MockWindow) SetFrameAttr(attr term.Attributes) (term.Attributes, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFrameAttr", attr)
	ret0, _ := ret[0].(term.Attributes)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// SetFrameAttr indicates an expected call of SetFrameAttr.
func (mr *MockWindowMockRecorder) SetFrameAttr(attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFrameAttr", reflect.TypeOf((*MockWindow)(nil).SetFrameAttr), attr)
}

// Unminimize mocks base method.
func (m *MockWindow) Unminimize() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unminimize")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Unminimize indicates an expected call of Unminimize.
func (mr *MockWindowMockRecorder) Unminimize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unminimize", reflect.TypeOf((*MockWindow)(nil).Unminimize))
}

// Width mocks base method.
func (m *MockWindow) Width() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width.
func (mr *MockWindowMockRecorder) Width() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Width", reflect.TypeOf((*MockWindow)(nil).Width))
}

// WindowID mocks base method.
func (m *MockWindow) WindowID() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WindowID")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// WindowID indicates an expected call of WindowID.
func (mr *MockWindowMockRecorder) WindowID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WindowID", reflect.TypeOf((*MockWindow)(nil).WindowID))
}

// MockWindowManager is a mock of WindowManager interface.
type MockWindowManager struct {
	ctrl     *gomock.Controller
	recorder *MockWindowManagerMockRecorder
}

// MockWindowManagerMockRecorder is the mock recorder for MockWindowManager.
type MockWindowManagerMockRecorder struct {
	mock *MockWindowManager
}

// NewMockWindowManager creates a new mock instance.
func NewMockWindowManager(ctrl *gomock.Controller) *MockWindowManager {
	mock := &MockWindowManager{ctrl: ctrl}
	mock.recorder = &MockWindowManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindowManager) EXPECT() *MockWindowManagerMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockWindowManager) Bar(arg0 browserapi.BarConfig, arg1 tui.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bar", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bar indicates an expected call of Bar.
func (mr *MockWindowManagerMockRecorder) Bar(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockWindowManager)(nil).Bar), arg0, arg1)
}

// Floating mocks base method.
func (m *MockWindowManager) Floating(h browser.Floating, cfg browserapi.FloatingConfig) (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Floating", h, cfg)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Floating indicates an expected call of Floating.
func (mr *MockWindowManagerMockRecorder) Floating(h, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Floating", reflect.TypeOf((*MockWindowManager)(nil).Floating), h, cfg)
}

// Focus mocks base method.
func (m *MockWindowManager) Focus() (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Focus")
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Focus indicates an expected call of Focus.
func (mr *MockWindowManagerMockRecorder) Focus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Focus", reflect.TypeOf((*MockWindowManager)(nil).Focus))
}

// IterateWindows mocks base method.
func (m *MockWindowManager) IterateWindows(fn func(browser.Window)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IterateWindows", fn)
}

// IterateWindows indicates an expected call of IterateWindows.
func (mr *MockWindowManagerMockRecorder) IterateWindows(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IterateWindows", reflect.TypeOf((*MockWindowManager)(nil).IterateWindows), fn)
}

// OnTabExit mocks base method.
func (m *MockWindowManager) OnTabExit(uri workspaceapi.URI) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnTabExit", uri)
	ret0, _ := ret[0].(bool)
	return ret0
}

// OnTabExit indicates an expected call of OnTabExit.
func (mr *MockWindowManagerMockRecorder) OnTabExit(uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTabExit", reflect.TypeOf((*MockWindowManager)(nil).OnTabExit), uri)
}

// SetFocus mocks base method.
func (m *MockWindowManager) SetFocus(win browser.Window) (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocus", win)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFocus indicates an expected call of SetFocus.
func (mr *MockWindowManagerMockRecorder) SetFocus(win any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocus", reflect.TypeOf((*MockWindowManager)(nil).SetFocus), win)
}

// SetTabActivity mocks base method.
func (m *MockWindowManager) SetTabActivity(uri workspaceapi.URI, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTabActivity", uri, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTabActivity indicates an expected call of SetTabActivity.
func (mr *MockWindowManagerMockRecorder) SetTabActivity(uri, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTabActivity", reflect.TypeOf((*MockWindowManager)(nil).SetTabActivity), uri, active)
}

// SetTabName mocks base method.
func (m *MockWindowManager) SetTabName(arg0 workspaceapi.URI, arg1 string, arg2 term.Attributes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTabName", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTabName indicates an expected call of SetTabName.
func (mr *MockWindowManagerMockRecorder) SetTabName(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTabName", reflect.TypeOf((*MockWindowManager)(nil).SetTabName), arg0, arg1, arg2)
}

// Split mocks base method.
func (m *MockWindowManager) Split(arg0 browserapi.Orientation, arg1 browser.Window, arg2 browserapi.Handler) (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Split", arg0, arg1, arg2)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Split indicates an expected call of Split.
func (mr *MockWindowManagerMockRecorder) Split(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Split", reflect.TypeOf((*MockWindowManager)(nil).Split), arg0, arg1, arg2)
}

// Tab mocks base method.
func (m *MockWindowManager) Tab(uri workspaceapi.URI, icon rune, name string, h browserapi.Handler) (browserapi.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tab", uri, icon, name, h)
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tab indicates an expected call of Tab.
func (mr *MockWindowManagerMockRecorder) Tab(uri, icon, name, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tab", reflect.TypeOf((*MockWindowManager)(nil).Tab), uri, icon, name, h)
}

// Window mocks base method.
func (m *MockWindowManager) Window(arg0 uint64) (browser.Window, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Window", arg0)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Window indicates an expected call of Window.
func (mr *MockWindowManagerMockRecorder) Window(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Window", reflect.TypeOf((*MockWindowManager)(nil).Window), arg0)
}

// MockTabManager is a mock of TabManager interface.
type MockTabManager struct {
	ctrl     *gomock.Controller
	recorder *MockTabManagerMockRecorder
}

// MockTabManagerMockRecorder is the mock recorder for MockTabManager.
type MockTabManagerMockRecorder struct {
	mock *MockTabManager
}

// NewMockTabManager creates a new mock instance.
func NewMockTabManager(ctrl *gomock.Controller) *MockTabManager {
	mock := &MockTabManager{ctrl: ctrl}
	mock.recorder = &MockTabManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTabManager) EXPECT() *MockTabManagerMockRecorder {
	return m.recorder
}

// OnTabExit mocks base method.
func (m *MockTabManager) OnTabExit(uri workspaceapi.URI) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnTabExit", uri)
	ret0, _ := ret[0].(bool)
	return ret0
}

// OnTabExit indicates an expected call of OnTabExit.
func (mr *MockTabManagerMockRecorder) OnTabExit(uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTabExit", reflect.TypeOf((*MockTabManager)(nil).OnTabExit), uri)
}

// SetTabActivity mocks base method.
func (m *MockTabManager) SetTabActivity(uri workspaceapi.URI, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTabActivity", uri, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTabActivity indicates an expected call of SetTabActivity.
func (mr *MockTabManagerMockRecorder) SetTabActivity(uri, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTabActivity", reflect.TypeOf((*MockTabManager)(nil).SetTabActivity), uri, active)
}

// SetTabName mocks base method.
func (m *MockTabManager) SetTabName(arg0 workspaceapi.URI, arg1 string, arg2 term.Attributes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTabName", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTabName indicates an expected call of SetTabName.
func (mr *MockTabManagerMockRecorder) SetTabName(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTabName", reflect.TypeOf((*MockTabManager)(nil).SetTabName), arg0, arg1, arg2)
}

// Tab mocks base method.
func (m *MockTabManager) Tab(uri workspaceapi.URI, icon rune, name string, h browserapi.Handler) (browserapi.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tab", uri, icon, name, h)
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tab indicates an expected call of Tab.
func (mr *MockTabManagerMockRecorder) Tab(uri, icon, name, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tab", reflect.TypeOf((*MockTabManager)(nil).Tab), uri, icon, name, h)
}

// MockNotifications is a mock of Notifications interface.
type MockNotifications struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsMockRecorder
}

// MockNotificationsMockRecorder is the mock recorder for MockNotifications.
type MockNotificationsMockRecorder struct {
	mock *MockNotifications
}

// NewMockNotifications creates a new mock instance.
func NewMockNotifications(ctrl *gomock.Controller) *MockNotifications {
	mock := &MockNotifications{ctrl: ctrl}
	mock.recorder = &MockNotificationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifications) EXPECT() *MockNotificationsMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotifications) Notify(level browserapi.NotificationLevel, msg string, args ...any) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{level, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Notify", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Notify indicates an expected call of Notify.
func (mr *MockNotificationsMockRecorder) Notify(level, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifications)(nil).Notify), varargs...)
}

// NotifyOnce mocks base method.
func (m *MockNotifications) NotifyOnce(level browserapi.NotificationLevel, msg string, args ...any) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{level, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NotifyOnce", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOnce indicates an expected call of NotifyOnce.
func (mr *MockNotificationsMockRecorder) NotifyOnce(level, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOnce", reflect.TypeOf((*MockNotifications)(nil).NotifyOnce), varargs...)
}

// UpdateNotificationProgress mocks base method.
func (m *MockNotifications) UpdateNotificationProgress(id, message string, progress, total int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationProgress", id, message, progress, total)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationProgress indicates an expected call of UpdateNotificationProgress.
func (mr *MockNotificationsMockRecorder) UpdateNotificationProgress(id, message, progress, total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationProgress", reflect.TypeOf((*MockNotifications)(nil).UpdateNotificationProgress), id, message, progress, total)
}

// MockResourceOpener is a mock of ResourceOpener interface.
type MockResourceOpener struct {
	ctrl     *gomock.Controller
	recorder *MockResourceOpenerMockRecorder
}

// MockResourceOpenerMockRecorder is the mock recorder for MockResourceOpener.
type MockResourceOpenerMockRecorder struct {
	mock *MockResourceOpener
}

// NewMockResourceOpener creates a new mock instance.
func NewMockResourceOpener(ctrl *gomock.Controller) *MockResourceOpener {
	mock := &MockResourceOpener{ctrl: ctrl}
	mock.recorder = &MockResourceOpenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceOpener) EXPECT() *MockResourceOpenerMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockResourceOpener) Open(resource workspaceapi.URI) (browserapi.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", resource)
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockResourceOpenerMockRecorder) Open(resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockResourceOpener)(nil).Open), resource)
}

// Resource mocks base method.
func (m *MockResourceOpener) Resource(arg0 workspaceapi.URI) (browserapi.Handler, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resource", arg0)
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Resource indicates an expected call of Resource.
func (mr *MockResourceOpenerMockRecorder) Resource(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resource", reflect.TypeOf((*MockResourceOpener)(nil).Resource), arg0)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishEvent mocks base method.
func (m *MockEventPublisher) PublishEvent(arg0 term.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockEventPublisherMockRecorder) PublishEvent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEvent", reflect.TypeOf((*MockEventPublisher)(nil).PublishEvent), arg0)
}

// MockDragTarget is a mock of DragTarget interface.
type MockDragTarget struct {
	ctrl     *gomock.Controller
	recorder *MockDragTargetMockRecorder
}

// MockDragTargetMockRecorder is the mock recorder for MockDragTarget.
type MockDragTargetMockRecorder struct {
	mock *MockDragTarget
}

// NewMockDragTarget creates a new mock instance.
func NewMockDragTarget(ctrl *gomock.Controller) *MockDragTarget {
	mock := &MockDragTarget{ctrl: ctrl}
	mock.recorder = &MockDragTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDragTarget) EXPECT() *MockDragTargetMockRecorder {
	return m.recorder
}

// DragCancel mocks base method.
func (m *MockDragTarget) DragCancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DragCancel")
}

// DragCancel indicates an expected call of DragCancel.
func (mr *MockDragTargetMockRecorder) DragCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DragCancel", reflect.TypeOf((*MockDragTarget)(nil).DragCancel))
}

// DragDrop mocks base method.
func (m *MockDragTarget) DragDrop(pos term.Coordinates, paths []string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DragDrop", pos, paths)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DragDrop indicates an expected call of DragDrop.
func (mr *MockDragTargetMockRecorder) DragDrop(pos, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DragDrop", reflect.TypeOf((*MockDragTarget)(nil).DragDrop), pos, paths)
}

// DragHover mocks base method.
func (m *MockDragTarget) DragHover(pos term.Coordinates) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DragHover", pos)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DragHover indicates an expected call of DragHover.
func (mr *MockDragTargetMockRecorder) DragHover(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DragHover", reflect.TypeOf((*MockDragTarget)(nil).DragHover), pos)
}

// MockBrowser is a mock of Browser interface.
type MockBrowser struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserMockRecorder
}

// MockBrowserMockRecorder is the mock recorder for MockBrowser.
type MockBrowserMockRecorder struct {
	mock *MockBrowser
}

// NewMockBrowser creates a new mock instance.
func NewMockBrowser(ctrl *gomock.Controller) *MockBrowser {
	mock := &MockBrowser{ctrl: ctrl}
	mock.recorder = &MockBrowserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowser) EXPECT() *MockBrowserMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockBrowser) Bar(arg0 browserapi.BarConfig, arg1 tui.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bar", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bar indicates an expected call of Bar.
func (mr *MockBrowserMockRecorder) Bar(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockBrowser)(nil).Bar), arg0, arg1)
}

// Close mocks base method.
func (m *MockBrowser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrowserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrowser)(nil).Close))
}

// DragCancel mocks base method.
func (m *MockBrowser) DragCancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DragCancel")
}

// DragCancel indicates an expected call of DragCancel.
func (mr *MockBrowserMockRecorder) DragCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DragCancel", reflect.TypeOf((*MockBrowser)(nil).DragCancel))
}

// DragDrop mocks base method.
func (m *MockBrowser) DragDrop(pos term.Coordinates, paths []string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DragDrop", pos, paths)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DragDrop indicates an expected call of DragDrop.
func (mr *MockBrowserMockRecorder) DragDrop(pos, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DragDrop", reflect.TypeOf((*MockBrowser)(nil).DragDrop), pos, paths)
}

// DragHover mocks base method.
func (m *MockBrowser) DragHover(pos term.Coordinates) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DragHover", pos)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DragHover indicates an expected call of DragHover.
func (mr *MockBrowserMockRecorder) DragHover(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DragHover", reflect.TypeOf((*MockBrowser)(nil).DragHover), pos)
}

// Floating mocks base method.
func (m *MockBrowser) Floating(h browser.Floating, cfg browserapi.FloatingConfig) (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Floating", h, cfg)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Floating indicates an expected call of Floating.
func (mr *MockBrowserMockRecorder) Floating(h, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Floating", reflect.TypeOf((*MockBrowser)(nil).Floating), h, cfg)
}

// Focus mocks base method.
func (m *MockBrowser) Focus() (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Focus")
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Focus indicates an expected call of Focus.
func (mr *MockBrowserMockRecorder) Focus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Focus", reflect.TypeOf((*MockBrowser)(nil).Focus))
}

// IterateWindows mocks base method.
func (m *MockBrowser) IterateWindows(fn func(browser.Window)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IterateWindows", fn)
}

// IterateWindows indicates an expected call of IterateWindows.
func (mr *MockBrowserMockRecorder) IterateWindows(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IterateWindows", reflect.TypeOf((*MockBrowser)(nil).IterateWindows), fn)
}

// Notify mocks base method.
func (m *MockBrowser) Notify(level browserapi.NotificationLevel, msg string, args ...any) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{level, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Notify", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Notify indicates an expected call of Notify.
func (mr *MockBrowserMockRecorder) Notify(level, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockBrowser)(nil).Notify), varargs...)
}

// NotifyOnce mocks base method.
func (m *MockBrowser) NotifyOnce(level browserapi.NotificationLevel, msg string, args ...any) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{level, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NotifyOnce", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOnce indicates an expected call of NotifyOnce.
func (mr *MockBrowserMockRecorder) NotifyOnce(level, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOnce", reflect.TypeOf((*MockBrowser)(nil).NotifyOnce), varargs...)
}

// OnTabExit mocks base method.
func (m *MockBrowser) OnTabExit(uri workspaceapi.URI) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnTabExit", uri)
	ret0, _ := ret[0].(bool)
	return ret0
}

// OnTabExit indicates an expected call of OnTabExit.
func (mr *MockBrowserMockRecorder) OnTabExit(uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTabExit", reflect.TypeOf((*MockBrowser)(nil).OnTabExit), uri)
}

// Open mocks base method.
func (m *MockBrowser) Open(resource workspaceapi.URI) (browserapi.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", resource)
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockBrowserMockRecorder) Open(resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockBrowser)(nil).Open), resource)
}

// PublishEvent mocks base method.
func (m *MockBrowser) PublishEvent(arg0 term.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockBrowserMockRecorder) PublishEvent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEvent", reflect.TypeOf((*MockBrowser)(nil).PublishEvent), arg0)
}

// Resource mocks base method.
func (m *MockBrowser) Resource(arg0 workspaceapi.URI) (browserapi.Handler, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resource", arg0)
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Resource indicates an expected call of Resource.
func (mr *MockBrowserMockRecorder) Resource(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resource", reflect.TypeOf((*MockBrowser)(nil).Resource), arg0)
}

// SetFocus mocks base method.
func (m *MockBrowser) SetFocus(win browser.Window) (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocus", win)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFocus indicates an expected call of SetFocus.
func (mr *MockBrowserMockRecorder) SetFocus(win any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocus", reflect.TypeOf((*MockBrowser)(nil).SetFocus), win)
}

// SetTabActivity mocks base method.
func (m *MockBrowser) SetTabActivity(uri workspaceapi.URI, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTabActivity", uri, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTabActivity indicates an expected call of SetTabActivity.
func (mr *MockBrowserMockRecorder) SetTabActivity(uri, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTabActivity", reflect.TypeOf((*MockBrowser)(nil).SetTabActivity), uri, active)
}

// SetTabName mocks base method.
func (m *MockBrowser) SetTabName(arg0 workspaceapi.URI, arg1 string, arg2 term.Attributes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTabName", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTabName indicates an expected call of SetTabName.
func (mr *MockBrowserMockRecorder) SetTabName(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTabName", reflect.TypeOf((*MockBrowser)(nil).SetTabName), arg0, arg1, arg2)
}

// Split mocks base method.
func (m *MockBrowser) Split(arg0 browserapi.Orientation, arg1 browser.Window, arg2 browserapi.Handler) (browser.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Split", arg0, arg1, arg2)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Split indicates an expected call of Split.
func (mr *MockBrowserMockRecorder) Split(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Split", reflect.TypeOf((*MockBrowser)(nil).Split), arg0, arg1, arg2)
}

// Tab mocks base method.
func (m *MockBrowser) Tab(uri workspaceapi.URI, icon rune, name string, h browserapi.Handler) (browserapi.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tab", uri, icon, name, h)
	ret0, _ := ret[0].(browserapi.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tab indicates an expected call of Tab.
func (mr *MockBrowserMockRecorder) Tab(uri, icon, name, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tab", reflect.TypeOf((*MockBrowser)(nil).Tab), uri, icon, name, h)
}

// UpdateNotificationProgress mocks base method.
func (m *MockBrowser) UpdateNotificationProgress(id, message string, progress, total int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationProgress", id, message, progress, total)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationProgress indicates an expected call of UpdateNotificationProgress.
func (mr *MockBrowserMockRecorder) UpdateNotificationProgress(id, message, progress, total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationProgress", reflect.TypeOf((*MockBrowser)(nil).UpdateNotificationProgress), id, message, progress, total)
}

// Window mocks base method.
func (m *MockBrowser) Window(arg0 uint64) (browser.Window, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Window", arg0)
	ret0, _ := ret[0].(browser.Window)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Window indicates an expected call of Window.
func (mr *MockBrowserMockRecorder) Window(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Window", reflect.TypeOf((*MockBrowser)(nil).Window), arg0)
}
