// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unstablebuild/rune-go-sdk/api/schemeapi (interfaces: Scheme)
//
// Generated by this command:
//
//	mockgen -destination=./schemetest/scheme_gomock.go -package schemetest github.com/unstablebuild/rune-go-sdk/api/schemeapi Scheme
//

// Package schemetest is a generated GoMock package.
package schemetest

import (
	context "context"
	fs "io/fs"
	reflect "reflect"
	syscall "syscall"

	schemeapi "github.com/unstablebuild/rune-go-sdk/api/schemeapi"
	workspaceapi "github.com/unstablebuild/rune-go-sdk/api/workspaceapi"
	gomock "go.uber.org/mock/gomock"
)

// MockScheme is a mock of Scheme interface.
type MockScheme struct {
	ctrl     *gomock.Controller
	recorder *MockSchemeMockRecorder
}

// MockSchemeMockRecorder is the mock recorder for MockScheme.
type MockSchemeMockRecorder struct {
	mock *MockScheme
}

// NewMockScheme creates a new mock instance.
func NewMockScheme(ctrl *gomock.Controller) *MockScheme {
	mock := &MockScheme{ctrl: ctrl}
	mock.recorder = &MockSchemeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheme) EXPECT() *MockSchemeMockRecorder {
	return m.recorder
}

// Chroot mocks base method.
func (m *MockScheme) Chroot(arg0 string) (schemeapi.Scheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chroot", arg0)
	ret0, _ := ret[0].(schemeapi.Scheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chroot indicates an expected call of Chroot.
func (mr *MockSchemeMockRecorder) Chroot(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chroot", reflect.TypeOf((*MockScheme)(nil).Chroot), arg0)
}

// Close mocks base method.
func (m *MockScheme) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSchemeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockScheme)(nil).Close))
}

// Create mocks base method.
func (m *MockScheme) Create(arg0 string) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSchemeMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheme)(nil).Create), arg0)
}

// Join mocks base method.
func (m *MockScheme) Join(arg0 ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockSchemeMockRecorder) Join(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockScheme)(nil).Join), arg0...)
}

// Lstat mocks base method.
func (m *MockScheme) Lstat(arg0 string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", arg0)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockSchemeMockRecorder) Lstat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockScheme)(nil).Lstat), arg0)
}

// MkdirAll mocks base method.
func (m *MockScheme) MkdirAll(arg0 string, arg1 fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockSchemeMockRecorder) MkdirAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockScheme)(nil).MkdirAll), arg0, arg1)
}

// NewFile mocks base method.
func (m *MockScheme) NewFile(arg0 uintptr, arg1 string) workspaceapi.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFile", arg0, arg1)
	ret0, _ := ret[0].(workspaceapi.File)
	return ret0
}

// NewFile indicates an expected call of NewFile.
func (mr *MockSchemeMockRecorder) NewFile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFile", reflect.TypeOf((*MockScheme)(nil).NewFile), arg0, arg1)
}

// NewPty mocks base method.
func (m *MockScheme) NewPty(arg0 context.Context) (workspaceapi.Pty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPty", arg0)
	ret0, _ := ret[0].(workspaceapi.Pty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPty indicates an expected call of NewPty.
func (mr *MockSchemeMockRecorder) NewPty(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPty", reflect.TypeOf((*MockScheme)(nil).NewPty), arg0)
}

// Open mocks base method.
func (m *MockScheme) Open(arg0 string) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", arg0)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockSchemeMockRecorder) Open(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockScheme)(nil).Open), arg0)
}

// OpenFile mocks base method.
func (m *MockScheme) OpenFile(arg0 string, arg1 int, arg2 fs.FileMode) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockSchemeMockRecorder) OpenFile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockScheme)(nil).OpenFile), arg0, arg1, arg2)
}

// ReadDir mocks base method.
func (m *MockScheme) ReadDir(arg0 string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", arg0)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockSchemeMockRecorder) ReadDir(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockScheme)(nil).ReadDir), arg0)
}

// Readlink mocks base method.
func (m *MockScheme) Readlink(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readlink", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readlink indicates an expected call of Readlink.
func (mr *MockSchemeMockRecorder) Readlink(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readlink", reflect.TypeOf((*MockScheme)(nil).Readlink), arg0)
}

// Remove mocks base method.
func (m *MockScheme) Remove(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockSchemeMockRecorder) Remove(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockScheme)(nil).Remove), arg0)
}

// Rename mocks base method.
func (m *MockScheme) Rename(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockSchemeMockRecorder) Rename(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockScheme)(nil).Rename), arg0, arg1)
}

// Root mocks base method.
func (m *MockScheme) Root() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Root")
	ret0, _ := ret[0].(string)
	return ret0
}

// Root indicates an expected call of Root.
func (mr *MockSchemeMockRecorder) Root() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Root", reflect.TypeOf((*MockScheme)(nil).Root))
}

// SetPtySize mocks base method.
func (m *MockScheme) SetPtySize(arg0 workspaceapi.Pty, arg1 workspaceapi.PtySize) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPtySize", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPtySize indicates an expected call of SetPtySize.
func (mr *MockSchemeMockRecorder) SetPtySize(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPtySize", reflect.TypeOf((*MockScheme)(nil).SetPtySize), arg0, arg1)
}

// Signal mocks base method.
func (m *MockScheme) Signal(arg0 workspaceapi.Pid, arg1 syscall.Signal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockSchemeMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockScheme)(nil).Signal), arg0, arg1)
}

// StartCommand mocks base method.
func (m *MockScheme) StartCommand(arg0 context.Context, arg1 workspaceapi.Cmd) (workspaceapi.Pid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCommand", arg0, arg1)
	ret0, _ := ret[0].(workspaceapi.Pid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartCommand indicates an expected call of StartCommand.
func (mr *MockSchemeMockRecorder) StartCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCommand", reflect.TypeOf((*MockScheme)(nil).StartCommand), arg0, arg1)
}

// Stat mocks base method.
func (m *MockScheme) Stat(arg0 string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", arg0)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockSchemeMockRecorder) Stat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockScheme)(nil).Stat), arg0)
}

// StopWatch mocks base method.
func (m *MockScheme) StopWatch(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopWatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopWatch indicates an expected call of StopWatch.
func (mr *MockSchemeMockRecorder) StopWatch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopWatch", reflect.TypeOf((*MockScheme)(nil).StopWatch), arg0)
}

// Symlink mocks base method.
func (m *MockScheme) Symlink(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockSchemeMockRecorder) Symlink(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockScheme)(nil).Symlink), arg0, arg1)
}

// TempFile mocks base method.
func (m *MockScheme) TempFile(arg0, arg1 string) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempFile", arg0, arg1)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempFile indicates an expected call of TempFile.
func (mr *MockSchemeMockRecorder) TempFile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempFile", reflect.TypeOf((*MockScheme)(nil).TempFile), arg0, arg1)
}

// URI mocks base method.
func (m *MockScheme) URI(arg0 string) (workspaceapi.URI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URI", arg0)
	ret0, _ := ret[0].(workspaceapi.URI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URI indicates an expected call of URI.
func (mr *MockSchemeMockRecorder) URI(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URI", reflect.TypeOf((*MockScheme)(nil).URI), arg0)
}

// Watch mocks base method.
func (m *MockScheme) Watch(arg0 string, arg1 chan<- schemeapi.EventInfo, arg2 ...schemeapi.Event) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockSchemeMockRecorder) Watch(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockScheme)(nil).Watch), varargs...)
}
