// Copyright (C) 2017-2026 The Rune Authors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// Command runewidthgen emits term/vte/rune_width.gen.go, a static
// lookup table for the monospace width of every codepoint below
// widthTableLimit.
//
// graphemecluster.StringWidth costs two Unicode table binary searches
// (grapheme break plus East Asian width) per call, and bulk non-ASCII
// output calls it once per codepoint. A flat table would be 128KiB of
// source, so codepoints are grouped into fixed-size blocks and
// identical blocks are shared: scripts are contiguous enough that a few
// hundred distinct blocks cover the whole range.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/unstablebuild/rune-go-sdk/term/graphemecluster"
)

// Must match the constants in term/vte/rune_width.go.
const (
	widthTableLimit = 0x20000
	widthBlockShift = 6
	widthBlockSize  = 1 << widthBlockShift
)

const header = `// Copyright (C) 2017-2026 The Rune Authors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

`

func main() {
	_, self, _, _ := runtime.Caller(0)
	defaultOut := filepath.Join(filepath.Dir(filepath.Dir(self)), "rune_width.gen.go")
	out := flag.String("out", defaultOut, "path of the generated file")
	flag.Parse()

	blocks, index := buildTable()
	emit(*out, blocks, index)
}

// buildTable returns the deduplicated width blocks and, for each block
// of codepoints, the index of the block holding its widths.
func buildTable() (blocks []string, index []byte) {
	ids := make(map[string]int)
	for c := 0; c < widthTableLimit; c += widthBlockSize {
		widths := make([]byte, widthBlockSize)
		for i := range widths {
			w := graphemecluster.StringWidth(string(rune(c + i)))
			if w < 0 || w > 9 {
				panic(fmt.Sprintf("width %d of %U does not fit in a digit", w, rune(c+i)))
			}
			widths[i] = byte('0' + w)
		}
		key := string(widths)
		id, ok := ids[key]
		if !ok {
			id = len(blocks)
			ids[key] = id
			blocks = append(blocks, key)
		}
		if id > 0xFF {
			panic("block index no longer fits in a byte")
		}
		index = append(index, byte(id))
	}
	return blocks, index
}

func emit(path string, blocks []string, index []byte) {
	f, err := os.Create(path)
	must(err)
	defer f.Close()
	w := bufio.NewWriter(f)
	defer func() { must(w.Flush()) }()

	fmt.Fprintf(w, "%s// Code generated by runewidthgen. DO NOT EDIT.\n\npackage vte\n\n", header)

	fmt.Fprintf(w, "// runeWidthBlocks holds the width of each codepoint as an ASCII\n")
	fmt.Fprintf(w, "// digit, one %d-codepoint block per line, with identical blocks\n", widthBlockSize)
	fmt.Fprintf(w, "// stored once and shared through runeWidthBlockIndex.\n")
	fmt.Fprintf(w, "const runeWidthBlocks = \"\" +\n")
	for i, block := range blocks {
		sep := " +"
		if i == len(blocks)-1 {
			sep = ""
		}
		fmt.Fprintf(w, "\t%q%s\n", block, sep)
	}

	fmt.Fprintf(w, "\n// runeWidthBlockIndex maps each %d-codepoint block to its block in\n", widthBlockSize)
	fmt.Fprintf(w, "// runeWidthBlocks.\n")
	fmt.Fprintf(w, "const runeWidthBlockIndex = \"\" +\n")
	const perLine = 16
	for i := 0; i < len(index); i += perLine {
		end := min(i+perLine, len(index))
		fmt.Fprint(w, "\t\"")
		for _, b := range index[i:end] {
			fmt.Fprintf(w, "\\x%02x", b)
		}
		sep := " +"
		if end == len(index) {
			sep = ""
		}
		fmt.Fprintf(w, "\"%s\n", sep)
	}
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
