// Copyright (C) 2017-2026 The Rune Authors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package ide

import (
	"cmp"
	_ "embed"
	"fmt"
	"slices"
	"strings"
	"text/template"

	"github.com/unstablebuild/rune-go-sdk/term"
	"unstable.build/rune/internal/handler/command"
	"unstable.build/rune/internal/ide/idetutorial/starlarktutorial"
	"unstable.build/rune/internal/text"
)

//go:embed keybindings.md.tmpl
var keybindingsTmplSrc string

var keybindingsTmpl = template.Must(
	template.New("keybindings").Parse(keybindingsTmplSrc))

// keybindingsWidth is the fixed width of the key bindings floating
// window. Wider than cheatsheetWidth because entries carry a key, a
// command line, and a full manual summary on one line; the window
// manager clamps it on smaller terminals.
const keybindingsWidth = 150

// keyBindingCategory groups bindings into a titled, documented section
// by whitelisting command matchers. An entry may span several tokens
// ("lsp diagnostics"): leading tokens match argv exactly and the final
// token by prefix. Categories are rendered in declaration order; the
// final catch-all (nil Prefixes) collects every binding no category
// claimed.
type keyBindingCategory struct {
	Title    string
	Doc      string
	Prefixes []string
}

var keyBindingCategories = []keyBindingCategory{
	{
		Title: "Language intelligence",
		Doc: "Code queries and navigation powered by the language server and " +
			"syntax-aware jumps: completion, hovers, definitions, and references.",
		Prefixes: []string{"lsp", "jumptoast"},
	},
	{
		Title: "Code navigation",
		Doc: "Move around the codebase: file explorer, fuzzy text and symbol " +
			"search, diagnostics, source-control changes, and cursor history.",
		Prefixes: []string{
			"fexplorer", "search", "lspnextdiagnostic", "lspprevdiagnostic",
			"gitnextchange", "gitprevchange", "cursorhistory next",
			"cursorhistory prev", "lsp diagnostics",
		},
	},
	{
		Title:    "Windows",
		Doc:      "Create, focus, move, resize, and close windows within a workspace.",
		Prefixes: []string{"window"},
	},
	{
		Title:    "Tabs",
		Doc:      "Open, close, focus, and rearrange tabs inside a window.",
		Prefixes: []string{"tab"},
	},
	{
		Title:    "Workspaces",
		Doc:      "Open, switch between, and rearrange workspaces.",
		Prefixes: []string{"workspace"},
	},
	{
		Title:    "Marks and locations",
		Doc:      "Set marks and jump between the locations saved on location lists.",
		Prefixes: []string{"location", "jumptolocation"},
	},
	{
		Title: "Other",
		Doc:   "Everything else bound in your configuration.",
	},
}

// keyBindingRow is one rendered entry of a key bindings list.
type keyBindingRow struct {
	Key     string
	Command string
	Action  string
}

// keyBindingSection is one rendered category of the key bindings view.
type keyBindingSection struct {
	Title string
	Doc   string
	Rows  []keyBindingRow
}

// keybindingsData is the template context for keybindings.md.tmpl.
// Other is split from Sections so the template can interleave the
// hand-authored macros section between the categorized lists and the
// trailing catch-all.
type keybindingsData struct {
	EditorMode string
	// MetaKey names the key behind `<meta>`, and is empty when no binding
	// uses it, as with every Linux preset.
	MetaKey  string
	Sections []keyBindingSection
	Other    *keyBindingSection
}

// kbEntry is one effective binding before compression and rendering.
// prefix holds the leading chord of a sequence binding ("" for single
// chords); spec holds the trailing chord, which is the one that varies
// in autogenerated families such as tabfocus 1-9 or the a-z marks.
type kbEntry struct {
	prefix string
	spec   string
	ch     rune
	cmds   [][]string
}

func (e kbEntry) key() string { return e.prefix + e.spec }

// renderKeyBindings enumerates every effective key binding on cfg and
// renders them as categorized Markdown lists. Unlike the cheatsheet,
// which resolves keys for a curated command list, this reflects the
// user's actual configured bindings (defaults + config + modal vi
// built-ins). Autogenerated families that vary only by a digit or
// letter present in both the key and the command (tabfocus 1-9, the
// a-z mark bindings) are compressed into a single <key-X> entry.
func renderKeyBindings(cfg text.Config, cmdManuals []command.Manual, editorMode, goos string) (string, error) {
	manuals := make(map[string]command.Manual, len(cmdManuals))
	for _, m := range cmdManuals {
		manuals[m.Name] = m
	}

	sections := make([]keyBindingSection, len(keyBindingCategories))
	for i, cat := range keyBindingCategories {
		sections[i] = keyBindingSection{Title: cat.Title, Doc: cat.Doc}
	}
	addRow := func(key string, cmds [][]string, xRange string) {
		argv, prefill := keyBindingArgv(cmds)
		expanded, aliasPrefill := expandAliases(argv, cfg.CommandAliases)
		row := keyBindingRow{
			Key:     mdCode(key),
			Command: mdBold(joinCommandLines(cmds)),
			Action: mdText(keyBindingAction(
				manuals, argv, expanded, prefill || aliasPrefill, xRange)),
		}
		i := keyBindingCategoryIndex(argv)
		sections[i].Rows = append(sections[i].Rows, row)
	}

	singles, groups := compressKeyBindings(collectKeyBindingEntries(cfg))
	for _, g := range groups {
		addRow(g.key, g.cmds, rangeLabel(g.chars))
	}
	for _, e := range singles {
		addRow(e.key(), e.cmds, "")
	}

	data := keybindingsData{EditorMode: editorMode}
	if bindsMeta(cfg) {
		data.MetaKey = metaKeyName(goos)
	}
	for i := range sections {
		s := &sections[i]
		if len(s.Rows) == 0 {
			continue
		}
		slices.SortFunc(s.Rows, func(a, b keyBindingRow) int {
			return cmp.Or(
				strings.Compare(a.Key, b.Key),
				strings.Compare(a.Command, b.Command))
		})
		if i == len(sections)-1 {
			data.Other = s
			continue
		}
		data.Sections = append(data.Sections, *s)
	}

	var b strings.Builder
	if err := keybindingsTmpl.Execute(&b, data); err != nil {
		return "", fmt.Errorf("execute keybindings template: %w", err)
	}
	return b.String(), nil
}

// metaKeyName names the physical key that produces <meta> chords on the
// user's platform.
func metaKeyName(goos string) string {
	if goos == "darwin" {
		return "the Command key"
	}
	return "the Windows or Super key"
}

func bindsMeta(cfg text.Config) bool {
	for kc := range cfg.CommandKeyBindings {
		if kc.Mod&term.ModMeta != 0 {
			return true
		}
	}
	for seq := range cfg.CommandSequenceBindings {
		if (seq.First.Mod|seq.Last.Mod)&term.ModMeta != 0 {
			return true
		}
	}
	return false
}

func collectKeyBindingEntries(cfg text.Config) []kbEntry {
	var entries []kbEntry
	for kc, cmds := range cfg.CommandKeyBindings {
		entries = append(entries, kbEntry{
			spec: starlarktutorial.PrettyKeySpec(kc.String()),
			ch:   kc.Ch,
			cmds: cmds,
		})
	}
	for seq, cmds := range cfg.CommandSequenceBindings {
		entries = append(entries, kbEntry{
			prefix: starlarktutorial.PrettyKeySpec(seq.First.String()),
			spec:   starlarktutorial.PrettyKeySpec(seq.Last.String()),
			ch:     seq.Last.Ch,
			cmds:   cmds,
		})
	}
	return entries
}

// kbGroup is a compressed family of bindings that differ only by one
// digit or letter, rendered as a single row with X as the placeholder.
type kbGroup struct {
	key   string
	cmds  [][]string
	chars []rune
}

// compressKeyBindings partitions entries into compressed groups and
// leftover singles. A family is compressed only when at least three
// members share the same templated key and command, so coincidental
// pairs keep their explicit rows.
func compressKeyBindings(entries []kbEntry) ([]kbEntry, []kbGroup) {
	type candidate struct {
		group kbGroup
		orig  []kbEntry
	}
	candidates := make(map[string]*candidate)
	var singles []kbEntry

	for _, e := range entries {
		class := kbCharClass(e.ch)
		tmplSpec, ok := templateKeySpec(e.spec, e.ch)
		if class == 0 || !ok {
			singles = append(singles, e)
			continue
		}
		tmplCmds, replaced := replaceCommandTokens(e.cmds, string(e.ch))
		if replaced == 0 {
			singles = append(singles, e)
			continue
		}
		key := e.prefix + tmplSpec
		id := string(class) + "\x00" + key + "\x00" + joinCommandLines(tmplCmds)
		c := candidates[id]
		if c == nil {
			c = &candidate{group: kbGroup{key: key, cmds: tmplCmds}}
			candidates[id] = c
		}
		c.group.chars = append(c.group.chars, e.ch)
		c.orig = append(c.orig, e)
	}

	var groups []kbGroup
	for _, c := range candidates {
		if len(c.group.chars) >= 3 {
			groups = append(groups, c.group)
		} else {
			singles = append(singles, c.orig...)
		}
	}
	return singles, groups
}

func kbCharClass(c rune) rune {
	switch {
	case c >= '1' && c <= '9':
		return 'd'
	case c >= 'a' && c <= 'z':
		return 'l'
	}
	return 0
}

// templateKeySpec rewrites a rendered key spec so its varying character
// reads as X: "<alt-1>" becomes "<alt-X>" and "a" becomes "X". It
// substitutes only the trailing character position so modifier names
// (e.g. the "a" in "<alt-...>") are never touched.
func templateKeySpec(spec string, ch rune) (string, bool) {
	s := string(ch)
	if spec == s {
		return "X", true
	}
	if strings.HasSuffix(spec, s+">") {
		return spec[:len(spec)-len(s)-1] + "X>", true
	}
	return "", false
}

func replaceCommandTokens(cmds [][]string, tok string) ([][]string, int) {
	replaced := 0
	out := make([][]string, len(cmds))
	for i, line := range cmds {
		outLine := make([]string, len(line))
		for j, t := range line {
			if t == tok {
				outLine[j] = "X"
				replaced++
			} else {
				outLine[j] = t
			}
		}
		out[i] = outLine
	}
	return out, replaced
}

func rangeLabel(chars []rune) string {
	slices.Sort(chars)
	contiguous := true
	for i := 1; i < len(chars); i++ {
		if chars[i] != chars[i-1]+1 {
			contiguous = false
			break
		}
	}
	if contiguous {
		return fmt.Sprintf("X = %c-%c", chars[0], chars[len(chars)-1])
	}
	parts := make([]string, len(chars))
	for i, c := range chars {
		parts[i] = string(c)
	}
	return "X = " + strings.Join(parts, ", ")
}

func joinCommandLines(cmds [][]string) string {
	lines := make([]string, len(cmds))
	for i, c := range cmds {
		lines[i] = strings.Join(c, " ")
	}
	return strings.Join(lines, "; ")
}

// keyBindingArgv resolves the command line a binding is judged by for
// categorization and manual lookup. Prompt-prefill macros
// ("echo {prompt}lsp<space>hover<space>") are judged by the prefilled
// command line, not by echo. Aliases are left unexpanded so bindings
// are categorized by the name the user bound (lspnextdiagnostic stays
// under language intelligence even though it targets jumptolocation).
func keyBindingArgv(cmds [][]string) (argv []string, prefill bool) {
	if len(cmds) == 0 || len(cmds[0]) == 0 {
		return nil, false
	}
	return parsePromptPrefill(cmds[0])
}

// parsePromptPrefill rewrites an echo prompt-prefill macro
// ("echo {prompt}edit<space>") to the command line it prefills.
// Non-prefill argv passes through unchanged.
func parsePromptPrefill(argv []string) ([]string, bool) {
	if len(argv) > 1 && argv[0] == "echo" && strings.HasPrefix(argv[1], "{prompt}") {
		prefill := strings.TrimPrefix(strings.Join(argv[1:], " "), "{prompt}")
		return strings.Fields(strings.ReplaceAll(prefill, "<space>", " ")), true
	}
	return argv, false
}

// expandAliases rewrites argv through config aliases (lspnextdiagnostic
// -> jumptolocation next lsp-diagnostics) so the alias target's manual
// documents the binding. Alias targets that are themselves prompt-prefill
// macros (tabnew -> echo {prompt}edit<space>) resolve to the prefilled
// command so echo's manual never documents them.
func expandAliases(argv []string, aliases map[string]text.CommandAlias) ([]string, bool) {
	prefill := false
	// Cap expansion depth: aliases may reference other aliases, and a
	// misconfigured cycle must not hang rendering.
	for range 4 {
		if len(argv) == 0 {
			return argv, prefill
		}
		a, ok := aliases[argv[0]]
		if !ok || len(a.Commands) == 0 {
			return argv, prefill
		}
		expanded := strings.Fields(a.Commands[0])
		if len(expanded) == 0 {
			return argv, prefill
		}
		var p bool
		argv, p = parsePromptPrefill(append(expanded, argv[1:]...))
		prefill = prefill || p
	}
	return argv, prefill
}

// keyBindingCategoryIndex picks the category whose longest whitelist
// entry matches argv, so specific listings such as "lsp diagnostics"
// out-rank the broader "lsp" prefix regardless of category order. Ties
// go to the earlier category; no match lands in the trailing catch-all.
func keyBindingCategoryIndex(argv []string) int {
	best := len(keyBindingCategories) - 1
	bestScore := 0
	for i, cat := range keyBindingCategories {
		for _, entry := range cat.Prefixes {
			if score := categoryMatchScore(argv, entry); score > bestScore {
				best, bestScore = i, score
			}
		}
	}
	return best
}

func categoryMatchScore(argv []string, entry string) int {
	tokens := strings.Fields(entry)
	if len(tokens) == 0 || len(argv) < len(tokens) {
		return 0
	}
	last := len(tokens) - 1
	for i, tok := range tokens[:last] {
		if argv[i] != tok {
			return 0
		}
	}
	if !strings.HasPrefix(argv[last], tokens[last]) {
		return 0
	}
	return len(entry)
}

// keyBindingOverrides hand-authors descriptions for bindings whose
// manual summary does not describe how the binding is actually wired.
// Matches use the category whitelist grammar. doc applies to bindings
// that dispatch the command immediately (which therefore act on the
// symbol at the cursor); prefillDoc applies to prompt-prefill macros
// (which stage the command for a typed argument). An empty field falls
// through to the manual summary.
var keyBindingOverrides = []struct {
	match      string
	doc        string
	prefillDoc string
}{
	{match: "jumptoast locals.scm local.definition.method",
		prefillDoc: "Jump to a function in the current file"},
	{match: "jumptoast locals.scm local.definition.function",
		prefillDoc: "Jump to a function in the current file"},
	{match: "jumptoast locals.scm local.definition.var",
		prefillDoc: "Jump to a variable in the current file"},
	{match: "jumptoast locals.scm local.definition.type",
		prefillDoc: "Jump to a type in the current file"},
	// The searchast macros dispatch immediately (<enter>), so the same
	// description fits direct and prefill forms.
	{match: "searchast locals.scm local.definition.method",
		doc:        "Fuzzy search a function in the workspace",
		prefillDoc: "Fuzzy search a function in the workspace"},
	{match: "searchast locals.scm local.definition.function",
		doc:        "Fuzzy search a function in the workspace",
		prefillDoc: "Fuzzy search a function in the workspace"},
	{match: "searchast locals.scm local.definition.var",
		doc:        "Fuzzy search a variable in the workspace",
		prefillDoc: "Fuzzy search a variable in the workspace"},
	{match: "searchast locals.scm local.definition.type",
		doc:        "Fuzzy search a type in the workspace",
		prefillDoc: "Fuzzy search a type in the workspace"},
	{match: "lsp definition",
		doc:        "Go to the definition of the symbol at the cursor",
		prefillDoc: "Go to a definition by symbol name"},
	{match: "lsp declaration",
		doc:        "Go to the declaration of the symbol at the cursor",
		prefillDoc: "Go to a declaration by symbol name"},
	{match: "lsp type-definition",
		doc:        "Go to the type definition of the symbol at the cursor",
		prefillDoc: "Go to a type definition by symbol name"},
	{match: "lsp implementation",
		doc:        "Find implementations of the symbol at the cursor",
		prefillDoc: "Find implementations by symbol name"},
	{match: "lsp references",
		doc:        "Find references to the symbol at the cursor",
		prefillDoc: "Find references by symbol name"},
	{match: "lsp hover",
		doc:        "Show documentation and types for the symbol at the cursor",
		prefillDoc: "Show documentation and types by symbol name"},
	// Config aliases are matched by their bound name (before
	// expansion), so these describe the binding's intent rather than
	// the generic jumptolocation summary of the expanded target.
	{match: "lspnextdiagnostic",
		doc: "Jump to the next LSP diagnostic in the file"},
	{match: "lspprevdiagnostic",
		doc: "Jump to the previous LSP diagnostic in the file"},
	{match: "gitnextchange",
		doc: "Jump to the next git change in the file"},
	{match: "gitprevchange",
		doc: "Jump to the previous git change in the file"},
	{match: "cursorhistory next",
		doc: "Jump forward to a more recently visited file or cursor position"},
	{match: "cursorhistory prev",
		doc: "Jump back to a previously visited file or cursor position"},
	{match: "searchtext",
		doc: "Fuzzy search content across the workspace"},
	{match: "searchfile",
		doc: "Fuzzy search a file by name across the workspace"},
}

// keyBindingAction resolves a binding's description: a whitelist
// override matched against the bound command line first and its alias
// expansion second (so aliases can be described by their bound name or
// their target), otherwise the deepest subcommand summary found walking
// the expanded argv down the manual tree.
func keyBindingAction(
	manuals map[string]command.Manual, boundArgv, argv []string, prefill bool, xRange string,
) string {
	action := keyBindingOverrideDoc(boundArgv, prefill)
	if action == "" {
		action = keyBindingOverrideDoc(argv, prefill)
	}
	if action == "" {
		action = keyBindingManualSummary(manuals, argv)
	}
	switch {
	case action == "":
		return xRange
	case xRange == "":
		return action
	default:
		return action + " (" + xRange + ")"
	}
}

func keyBindingOverrideDoc(argv []string, prefill bool) string {
	best, bestScore := "", 0
	for _, o := range keyBindingOverrides {
		doc := o.doc
		if prefill {
			doc = o.prefillDoc
		}
		if doc == "" {
			continue
		}
		if score := categoryMatchScore(argv, o.match); score > bestScore {
			best, bestScore = doc, score
		}
	}
	return best
}

func keyBindingManualSummary(manuals map[string]command.Manual, argv []string) string {
	if len(argv) == 0 {
		return ""
	}
	m, ok := manuals[argv[0]]
	if !ok {
		return ""
	}
	action := m.Summary
	for _, arg := range argv[1:] {
		sub, ok := findSubManual(m, arg)
		if !ok {
			break
		}
		if sub.Summary != "" {
			action = sub.Summary
		}
		m = sub
	}
	return action
}

func findSubManual(m command.Manual, name string) (command.Manual, bool) {
	for _, sub := range m.Commands {
		if sub.Name == name {
			return sub, true
		}
	}
	return command.Manual{}, false
}

// mdCode wraps s in a Markdown code span safe for a list entry: specs
// containing backticks (such as the <a-`> key or vi mark sequences)
// get double-backtick delimiters.
func mdCode(s string) string {
	s = mdText(s)
	if strings.Contains(s, "`") {
		return "`` " + s + " ``"
	}
	return "`" + s + "`"
}

// mdBold wraps s in a bold span for a list entry. The markdown
// component honors neither backslash escapes nor HTML entities, and it
// silently drops raw-HTML tags and emphasis markers, so command lines
// such as "echo {prompt}edit<space>" must be neutralized structurally:
// a zero-width space after each inline-significant rune breaks the
// construct (the <...> tag, the *, the _) while staying invisible, so
// the literal command text survives.
func mdBold(s string) string {
	s = mdText(s)
	if s == "" {
		return ""
	}
	var b strings.Builder
	b.WriteString("**")
	for _, r := range s {
		b.WriteRune(r)
		if strings.ContainsRune("<*_[]()&`", r) {
			b.WriteRune('\u200b')
		}
	}
	b.WriteString("**")
	return b.String()
}

// mdText sanitizes s for a single-line Markdown list entry: whitespace
// runs (including newlines in multi-paragraph manual summaries) join
// into single spaces so an entry never spills onto following lines.
func mdText(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
