// Code generated by MockGen. DO NOT EDIT.
// Source: text/editor.go
//
// Generated by this command:
//
//	mockgen -destination=text/texttest/editor_gomock.go -package texttest -self_package unstable.build/rune/internal/text/texttest -source text/editor.go
//

// Package texttest is a generated GoMock package.
package texttest

import (
	context "context"
	reflect "reflect"

	textapi "github.com/unstablebuild/rune-go-sdk/api/textapi"
	workspaceapi "github.com/unstablebuild/rune-go-sdk/api/workspaceapi"
	term "github.com/unstablebuild/rune-go-sdk/term"
	gomock "go.uber.org/mock/gomock"
	cell "unstable.build/rune/internal/cell"
	text "unstable.build/rune/internal/text"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// CellEditor mocks base method.
func (m *MockHandler) CellEditor() cell.Editor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CellEditor")
	ret0, _ := ret[0].(cell.Editor)
	return ret0
}

// CellEditor indicates an expected call of CellEditor.
func (mr *MockHandlerMockRecorder) CellEditor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CellEditor", reflect.TypeOf((*MockHandler)(nil).CellEditor))
}

// CellView mocks base method.
func (m *MockHandler) CellView() cell.View {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CellView")
	ret0, _ := ret[0].(cell.View)
	return ret0
}

// CellView indicates an expected call of CellView.
func (mr *MockHandlerMockRecorder) CellView() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CellView", reflect.TypeOf((*MockHandler)(nil).CellView))
}

// Close mocks base method.
func (m *MockHandler) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockHandlerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockHandler)(nil).Close))
}

// Cursor mocks base method.
func (m *MockHandler) Cursor() (term.Coordinates, term.CursorStyle, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(term.Coordinates)
	ret1, _ := ret[1].(term.CursorStyle)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Cursor indicates an expected call of Cursor.
func (mr *MockHandlerMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockHandler)(nil).Cursor))
}

// CursorAtScroll mocks base method.
func (m *MockHandler) CursorAtScroll() term.Coordinates {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorAtScroll")
	ret0, _ := ret[0].(term.Coordinates)
	return ret0
}

// CursorAtScroll indicates an expected call of CursorAtScroll.
func (mr *MockHandlerMockRecorder) CursorAtScroll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorAtScroll", reflect.TypeOf((*MockHandler)(nil).CursorAtScroll))
}

// Dimensions mocks base method.
func (m *MockHandler) Dimensions() (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dimensions")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Dimensions indicates an expected call of Dimensions.
func (mr *MockHandlerMockRecorder) Dimensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dimensions", reflect.TypeOf((*MockHandler)(nil).Dimensions))
}

// Draw mocks base method.
func (m *MockHandler) Draw(arg0 term.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Draw", arg0)
}

// Draw indicates an expected call of Draw.
func (mr *MockHandlerMockRecorder) Draw(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockHandler)(nil).Draw), arg0)
}

// Handle mocks base method.
func (m *MockHandler) Handle(arg0 term.Event) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockHandler)(nil).Handle), arg0)
}

// IsNormalMode mocks base method.
func (m *MockHandler) IsNormalMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNormalMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNormalMode indicates an expected call of IsNormalMode.
func (mr *MockHandlerMockRecorder) IsNormalMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNormalMode", reflect.TypeOf((*MockHandler)(nil).IsNormalMode))
}

// IsSearchMode mocks base method.
func (m *MockHandler) IsSearchMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSearchMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSearchMode indicates an expected call of IsSearchMode.
func (mr *MockHandlerMockRecorder) IsSearchMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSearchMode", reflect.TypeOf((*MockHandler)(nil).IsSearchMode))
}

// LocationLists mocks base method.
func (m *MockHandler) LocationLists() []text.LocationSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocationLists")
	ret0, _ := ret[0].([]text.LocationSet)
	return ret0
}

// LocationLists indicates an expected call of LocationLists.
func (mr *MockHandlerMockRecorder) LocationLists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocationLists", reflect.TypeOf((*MockHandler)(nil).LocationLists))
}

// MaxSeekOffset mocks base method.
func (m *MockHandler) MaxSeekOffset() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxSeekOffset")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxSeekOffset indicates an expected call of MaxSeekOffset.
func (mr *MockHandlerMockRecorder) MaxSeekOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxSeekOffset", reflect.TypeOf((*MockHandler)(nil).MaxSeekOffset))
}

// MoveToNextLocation mocks base method.
func (m *MockHandler) MoveToNextLocation(ID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToNextLocation", ID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MoveToNextLocation indicates an expected call of MoveToNextLocation.
func (mr *MockHandlerMockRecorder) MoveToNextLocation(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToNextLocation", reflect.TypeOf((*MockHandler)(nil).MoveToNextLocation), ID)
}

// MoveToPrevLocation mocks base method.
func (m *MockHandler) MoveToPrevLocation(ID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToPrevLocation", ID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MoveToPrevLocation indicates an expected call of MoveToPrevLocation.
func (mr *MockHandlerMockRecorder) MoveToPrevLocation(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToPrevLocation", reflect.TypeOf((*MockHandler)(nil).MoveToPrevLocation), ID)
}

// Resize mocks base method.
func (m *MockHandler) Resize(width, height int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resize", width, height)
}

// Resize indicates an expected call of Resize.
func (mr *MockHandlerMockRecorder) Resize(width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockHandler)(nil).Resize), width, height)
}

// Resource mocks base method.
func (m *MockHandler) Resource() workspaceapi.URI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resource")
	ret0, _ := ret[0].(workspaceapi.URI)
	return ret0
}

// Resource indicates an expected call of Resource.
func (mr *MockHandlerMockRecorder) Resource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resource", reflect.TypeOf((*MockHandler)(nil).Resource))
}

// SeekDown mocks base method.
func (m *MockHandler) SeekDown() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekDown")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SeekDown indicates an expected call of SeekDown.
func (mr *MockHandlerMockRecorder) SeekDown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekDown", reflect.TypeOf((*MockHandler)(nil).SeekDown))
}

// SeekOffset mocks base method.
func (m *MockHandler) SeekOffset() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekOffset")
	ret0, _ := ret[0].(int)
	return ret0
}

// SeekOffset indicates an expected call of SeekOffset.
func (mr *MockHandlerMockRecorder) SeekOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekOffset", reflect.TypeOf((*MockHandler)(nil).SeekOffset))
}

// SeekUp mocks base method.
func (m *MockHandler) SeekUp() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeekUp")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SeekUp indicates an expected call of SeekUp.
func (mr *MockHandlerMockRecorder) SeekUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekUp", reflect.TypeOf((*MockHandler)(nil).SeekUp))
}

// Selection mocks base method.
func (m *MockHandler) Selection() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selection")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Selection indicates an expected call of Selection.
func (mr *MockHandlerMockRecorder) Selection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selection", reflect.TypeOf((*MockHandler)(nil).Selection))
}

// SetCursorAtScroll mocks base method.
func (m *MockHandler) SetCursorAtScroll(pos term.Coordinates) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCursorAtScroll", pos)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetCursorAtScroll indicates an expected call of SetCursorAtScroll.
func (mr *MockHandlerMockRecorder) SetCursorAtScroll(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCursorAtScroll", reflect.TypeOf((*MockHandler)(nil).SetCursorAtScroll), pos)
}

// SetDefaultAttributes mocks base method.
func (m *MockHandler) SetDefaultAttributes(arg0 term.Attributes) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefaultAttributes", arg0)
}

// SetDefaultAttributes indicates an expected call of SetDefaultAttributes.
func (mr *MockHandlerMockRecorder) SetDefaultAttributes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultAttributes", reflect.TypeOf((*MockHandler)(nil).SetDefaultAttributes), arg0)
}

// SetLocationList mocks base method.
func (m *MockHandler) SetLocationList(arg0 textapi.LocationPriority, arg1 string, arg2 text.LocationList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLocationList", arg0, arg1, arg2)
}

// SetLocationList indicates an expected call of SetLocationList.
func (mr *MockHandlerMockRecorder) SetLocationList(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLocationList", reflect.TypeOf((*MockHandler)(nil).SetLocationList), arg0, arg1, arg2)
}

// SetWrap mocks base method.
func (m *MockHandler) SetWrap(wrap bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWrap", wrap)
}

// SetWrap indicates an expected call of SetWrap.
func (mr *MockHandlerMockRecorder) SetWrap(wrap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWrap", reflect.TypeOf((*MockHandler)(nil).SetWrap), wrap)
}

// ShowCommandBar mocks base method.
func (m *MockHandler) ShowCommandBar(show bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowCommandBar", show)
}

// ShowCommandBar indicates an expected call of ShowCommandBar.
func (mr *MockHandlerMockRecorder) ShowCommandBar(show any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowCommandBar", reflect.TypeOf((*MockHandler)(nil).ShowCommandBar), show)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// SubscribeEvents mocks base method.
func (m *MockEventPublisher) SubscribeEvents(arg0 []textapi.EventType, arg1 text.EventHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeEvents", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeEvents indicates an expected call of SubscribeEvents.
func (mr *MockEventPublisherMockRecorder) SubscribeEvents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEvents", reflect.TypeOf((*MockEventPublisher)(nil).SubscribeEvents), arg0, arg1)
}

// UnsubscribeEvents mocks base method.
func (m *MockEventPublisher) UnsubscribeEvents(arg0 text.EventHandler) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeEvents", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsubscribeEvents indicates an expected call of UnsubscribeEvents.
func (mr *MockEventPublisherMockRecorder) UnsubscribeEvents(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeEvents", reflect.TypeOf((*MockEventPublisher)(nil).UnsubscribeEvents), arg0)
}

// MockEditor is a mock of Editor interface.
type MockEditor struct {
	ctrl     *gomock.Controller
	recorder *MockEditorMockRecorder
}

// MockEditorMockRecorder is the mock recorder for MockEditor.
type MockEditorMockRecorder struct {
	mock *MockEditor
}

// NewMockEditor creates a new mock instance.
func NewMockEditor(ctrl *gomock.Controller) *MockEditor {
	mock := &MockEditor{ctrl: ctrl}
	mock.recorder = &MockEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditor) EXPECT() *MockEditorMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockEditor) Edit(ctx context.Context, file workspaceapi.URI, buf *cell.Buffer, readOnly, recovered bool) (text.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, file, buf, readOnly, recovered)
	ret0, _ := ret[0].(text.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit indicates an expected call of Edit.
func (mr *MockEditorMockRecorder) Edit(ctx, file, buf, readOnly, recovered any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockEditor)(nil).Edit), ctx, file, buf, readOnly, recovered)
}

// Editor mocks base method.
func (m *MockEditor) Editor(arg0 workspaceapi.URI) (text.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Editor", arg0)
	ret0, _ := ret[0].(text.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Editor indicates an expected call of Editor.
func (mr *MockEditorMockRecorder) Editor(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Editor", reflect.TypeOf((*MockEditor)(nil).Editor), arg0)
}

// IsExternal mocks base method.
func (m *MockEditor) IsExternal() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExternal")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExternal indicates an expected call of IsExternal.
func (mr *MockEditorMockRecorder) IsExternal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExternal", reflect.TypeOf((*MockEditor)(nil).IsExternal))
}

// RegisterREPLCommand mocks base method.
func (m *MockEditor) RegisterREPLCommand(arg0 textapi.CommandManual, arg1 textapi.REPLHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterREPLCommand", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterREPLCommand indicates an expected call of RegisterREPLCommand.
func (mr *MockEditorMockRecorder) RegisterREPLCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterREPLCommand", reflect.TypeOf((*MockEditor)(nil).RegisterREPLCommand), arg0, arg1)
}

// RegisterResourceOpener mocks base method.
func (m *MockEditor) RegisterResourceOpener(scheme string, h textapi.ResourceOpenHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterResourceOpener", scheme, h)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterResourceOpener indicates an expected call of RegisterResourceOpener.
func (mr *MockEditorMockRecorder) RegisterResourceOpener(scheme, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterResourceOpener", reflect.TypeOf((*MockEditor)(nil).RegisterResourceOpener), scheme, h)
}

// SubscribeCommand mocks base method.
func (m *MockEditor) SubscribeCommand(arg0 textapi.CommandManual, arg1 text.CommandHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeCommand", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeCommand indicates an expected call of SubscribeCommand.
func (mr *MockEditorMockRecorder) SubscribeCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeCommand", reflect.TypeOf((*MockEditor)(nil).SubscribeCommand), arg0, arg1)
}

// SubscribeEvents mocks base method.
func (m *MockEditor) SubscribeEvents(arg0 []textapi.EventType, arg1 text.EventHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeEvents", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeEvents indicates an expected call of SubscribeEvents.
func (mr *MockEditorMockRecorder) SubscribeEvents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEvents", reflect.TypeOf((*MockEditor)(nil).SubscribeEvents), arg0, arg1)
}

// UnregisterREPLCommand mocks base method.
func (m *MockEditor) UnregisterREPLCommand(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterREPLCommand", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterREPLCommand indicates an expected call of UnregisterREPLCommand.
func (mr *MockEditorMockRecorder) UnregisterREPLCommand(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterREPLCommand", reflect.TypeOf((*MockEditor)(nil).UnregisterREPLCommand), arg0)
}

// UnregisterResourceOpener mocks base method.
func (m *MockEditor) UnregisterResourceOpener(scheme string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterResourceOpener", scheme)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterResourceOpener indicates an expected call of UnregisterResourceOpener.
func (mr *MockEditorMockRecorder) UnregisterResourceOpener(scheme any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterResourceOpener", reflect.TypeOf((*MockEditor)(nil).UnregisterResourceOpener), scheme)
}

// UnsubscribeCommand mocks base method.
func (m *MockEditor) UnsubscribeCommand(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeCommand", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeCommand indicates an expected call of UnsubscribeCommand.
func (mr *MockEditorMockRecorder) UnsubscribeCommand(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeCommand", reflect.TypeOf((*MockEditor)(nil).UnsubscribeCommand), arg0)
}

// UnsubscribeEvents mocks base method.
func (m *MockEditor) UnsubscribeEvents(arg0 text.EventHandler) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeEvents", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsubscribeEvents indicates an expected call of UnsubscribeEvents.
func (mr *MockEditorMockRecorder) UnsubscribeEvents(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeEvents", reflect.TypeOf((*MockEditor)(nil).UnsubscribeEvents), arg0)
}
