// Code generated by MockGen. DO NOT EDIT.
// Source: ./component.go
//
// Generated by this command:
//
//	mockgen -destination=./texttest/workspace_gomock.go -package texttest -self_package unstable.build/rune/internal/text/texttest -source ./component.go
//

// Package texttest is a generated GoMock package.
package texttest

import (
	context "context"
	os "os"
	reflect "reflect"
	syscall "syscall"

	workspaceapi "github.com/unstablebuild/rune-go-sdk/api/workspaceapi"
	gomock "go.uber.org/mock/gomock"
	cell "unstable.build/rune/internal/cell"
	workspace "unstable.build/rune/internal/workspace"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWorkspace) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWorkspaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkspace)(nil).Close))
}

// Load mocks base method.
func (m *MockWorkspace) Load(file workspaceapi.URI, buf *cell.Buffer, swapDir workspaceapi.URI, readOnly bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", file, buf, swapDir, readOnly)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockWorkspaceMockRecorder) Load(file, buf, swapDir, readOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockWorkspace)(nil).Load), file, buf, swapDir, readOnly)
}

// Open mocks base method.
func (m *MockWorkspace) Open(arg0 string) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", arg0)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockWorkspaceMockRecorder) Open(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockWorkspace)(nil).Open), arg0)
}

// OpenFile mocks base method.
func (m *MockWorkspace) OpenFile(path string, flag int, perm os.FileMode) (workspaceapi.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", path, flag, perm)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockWorkspaceMockRecorder) OpenFile(path, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockWorkspace)(nil).OpenFile), path, flag, perm)
}

// PathCaseSensitive mocks base method.
func (m *MockWorkspace) PathCaseSensitive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathCaseSensitive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// PathCaseSensitive indicates an expected call of PathCaseSensitive.
func (mr *MockWorkspaceMockRecorder) PathCaseSensitive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathCaseSensitive", reflect.TypeOf((*MockWorkspace)(nil).PathCaseSensitive))
}

// ReadDir mocks base method.
func (m *MockWorkspace) ReadDir(name string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockWorkspaceMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockWorkspace)(nil).ReadDir), name)
}

// Recover mocks base method.
func (m *MockWorkspace) Recover(file, swapFilePath workspaceapi.URI, buf *cell.Buffer, force bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", file, swapFilePath, buf, force)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recover indicates an expected call of Recover.
func (mr *MockWorkspaceMockRecorder) Recover(file, swapFilePath, buf, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockWorkspace)(nil).Recover), file, swapFilePath, buf, force)
}

// Remove mocks base method.
func (m *MockWorkspace) Remove(file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWorkspaceMockRecorder) Remove(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWorkspace)(nil).Remove), file)
}

// Signal mocks base method.
func (m *MockWorkspace) Signal(arg0 workspaceapi.Pid, arg1 syscall.Signal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockWorkspaceMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockWorkspace)(nil).Signal), arg0, arg1)
}

// StartCommand mocks base method.
func (m *MockWorkspace) StartCommand(ctx context.Context, cmd workspaceapi.Cmd) (workspaceapi.Pid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCommand", ctx, cmd)
	ret0, _ := ret[0].(workspaceapi.Pid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartCommand indicates an expected call of StartCommand.
func (mr *MockWorkspaceMockRecorder) StartCommand(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCommand", reflect.TypeOf((*MockWorkspace)(nil).StartCommand), ctx, cmd)
}

// Stat mocks base method.
func (m *MockWorkspace) Stat(path string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", path)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockWorkspaceMockRecorder) Stat(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockWorkspace)(nil).Stat), path)
}

// URI mocks base method.
func (m *MockWorkspace) URI(arg0 string) (workspaceapi.URI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URI", arg0)
	ret0, _ := ret[0].(workspaceapi.URI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URI indicates an expected call of URI.
func (mr *MockWorkspaceMockRecorder) URI(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URI", reflect.TypeOf((*MockWorkspace)(nil).URI), arg0)
}
