// Copyright (C) 2017-2026 The Rune Authors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkgrpcpb/pkgrpc.proto

package pkgrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageError_Kind int32

const (
	PackageError_UNKNOWN            PackageError_Kind = 0
	PackageError_NOT_INSTALLED      PackageError_Kind = 1
	PackageError_PACKAGE_NOT_FOUND  PackageError_Kind = 2
	PackageError_VERSION_NOT_FOUND  PackageError_Kind = 3
	PackageError_ALREADY_INSTALLED  PackageError_Kind = 4
	PackageError_VERSION_IN_USE     PackageError_Kind = 5
	PackageError_SERVER_UNAVAILABLE PackageError_Kind = 6
	PackageError_ARTIFACT_MISSING   PackageError_Kind = 7
	PackageError_FORBIDDEN          PackageError_Kind = 8
	PackageError_NO_RELEASES        PackageError_Kind = 9
	PackageError_NOT_AUTHENTICATED  PackageError_Kind = 10
)

// Enum value maps for PackageError_Kind.
var (
	PackageError_Kind_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "NOT_INSTALLED",
		2:  "PACKAGE_NOT_FOUND",
		3:  "VERSION_NOT_FOUND",
		4:  "ALREADY_INSTALLED",
		5:  "VERSION_IN_USE",
		6:  "SERVER_UNAVAILABLE",
		7:  "ARTIFACT_MISSING",
		8:  "FORBIDDEN",
		9:  "NO_RELEASES",
		10: "NOT_AUTHENTICATED",
	}
	PackageError_Kind_value = map[string]int32{
		"UNKNOWN":            0,
		"NOT_INSTALLED":      1,
		"PACKAGE_NOT_FOUND":  2,
		"VERSION_NOT_FOUND":  3,
		"ALREADY_INSTALLED":  4,
		"VERSION_IN_USE":     5,
		"SERVER_UNAVAILABLE": 6,
		"ARTIFACT_MISSING":   7,
		"FORBIDDEN":          8,
		"NO_RELEASES":        9,
		"NOT_AUTHENTICATED":  10,
	}
)

func (x PackageError_Kind) Enum() *PackageError_Kind {
	p := new(PackageError_Kind)
	*p = x
	return p
}

func (x PackageError_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageError_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_pkgrpcpb_pkgrpc_proto_enumTypes[0].Descriptor()
}

func (PackageError_Kind) Type() protoreflect.EnumType {
	return &file_pkgrpcpb_pkgrpc_proto_enumTypes[0]
}

func (x PackageError_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageError_Kind.Descriptor instead.
func (PackageError_Kind) EnumDescriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{18, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{0}
}

type PackageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageRef) Reset() {
	*x = PackageRef{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRef) ProtoMessage() {}

func (x *PackageRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRef.ProtoReflect.Descriptor instead.
func (*PackageRef) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{1}
}

func (x *PackageRef) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type PackageVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageVersion) Reset() {
	*x = PackageVersion{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageVersion) ProtoMessage() {}

func (x *PackageVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageVersion.ProtoReflect.Descriptor instead.
func (*PackageVersion) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{2}
}

func (x *PackageVersion) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PackageVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       map[string]string      `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{3}
}

func (x *Filters) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PackageFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageFilters) Reset() {
	*x = PackageFilters{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageFilters) ProtoMessage() {}

func (x *PackageFilters) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageFilters.ProtoReflect.Descriptor instead.
func (*PackageFilters) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{4}
}

func (x *PackageFilters) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PackageFilters) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type DeleteVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVersionRequest) Reset() {
	*x = DeleteVersionRequest{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVersionRequest) ProtoMessage() {}

func (x *DeleteVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteVersionRequest) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteVersionRequest) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *DeleteVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeleteVersionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type Paths struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paths) Reset() {
	*x = Paths{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paths) ProtoMessage() {}

func (x *Paths) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paths.ProtoReflect.Descriptor instead.
func (*Paths) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{6}
}

func (x *Paths) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{7}
}

func (x *Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	InUse         bool                   `protobuf:"varint,2,opt,name=in_use,json=inUse,proto3" json:"in_use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InUse) Reset() {
	*x = InUse{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InUse) ProtoMessage() {}

func (x *InUse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InUse.ProtoReflect.Descriptor instead.
func (*InUse) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{8}
}

func (x *InUse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InUse) GetInUse() bool {
	if x != nil {
		return x.InUse
	}
	return false
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latest        string                 `protobuf:"bytes,2,opt,name=latest,proto3" json:"latest,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{9}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetLatest() string {
	if x != nil {
		return x.Latest
	}
	return ""
}

func (x *Package) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Package) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Package) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Bundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{10}
}

func (x *Bundle) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Bundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Bundle) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Bundle) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Bundle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      int64                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Units         string                 `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{11}
}

func (x *Progress) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Progress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Progress) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

// Notice is a notification the host's package manager emitted while it
// served the call, for the client to show in its own UI.
type Notice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// level is a browserapi.NotificationLevel.
	Level         uint32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Once          bool   `protobuf:"varint,3,opt,name=once,proto3" json:"once,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notice) Reset() {
	*x = Notice{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{12}
}

func (x *Notice) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Notice) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notice) GetOnce() bool {
	if x != nil {
		return x.Once
	}
	return false
}

// Prompt asks the client's user to approve a change to the host's user
// config.
type Prompt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// message is markdown.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// options[0] approves the change; every other option denies it.
	Options []*PromptOption `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	// max_width bounds the width of the prompt in cells; 0 sizes it to
	// the message.
	MaxWidth      uint32 `protobuf:"varint,4,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{13}
}

func (x *Prompt) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prompt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Prompt) GetOptions() []*PromptOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Prompt) GetMaxWidth() uint32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

type PromptOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// key is the character that picks the option, if any.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptOption) Reset() {
	*x = PromptOption{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptOption) ProtoMessage() {}

func (x *PromptOption) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptOption.ProtoReflect.Descriptor instead.
func (*PromptOption) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{14}
}

func (x *PromptOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PromptOption) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Answer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prompt is the id of the Prompt answered.
	Prompt        uint64 `protobuf:"varint,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Approved      bool   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{15}
}

func (x *Answer) GetPrompt() uint64 {
	if x != nil {
		return x.Prompt
	}
	return 0
}

func (x *Answer) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

// ChangeRequest is what a client sends on Install and Use: the package
// first, then an answer to every prompt the host sends.
type ChangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ChangeRequest_Package
	//	*ChangeRequest_Answer
	Request       isChangeRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest) Reset() {
	*x = ChangeRequest{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest) ProtoMessage() {}

func (x *ChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest.ProtoReflect.Descriptor instead.
func (*ChangeRequest) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeRequest) GetRequest() isChangeRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ChangeRequest) GetPackage() *PackageVersion {
	if x != nil {
		if x, ok := x.Request.(*ChangeRequest_Package); ok {
			return x.Package
		}
	}
	return nil
}

func (x *ChangeRequest) GetAnswer() *Answer {
	if x != nil {
		if x, ok := x.Request.(*ChangeRequest_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

type isChangeRequest_Request interface {
	isChangeRequest_Request()
}

type ChangeRequest_Package struct {
	Package *PackageVersion `protobuf:"bytes,1,opt,name=package,proto3,oneof"`
}

type ChangeRequest_Answer struct {
	Answer *Answer `protobuf:"bytes,2,opt,name=answer,proto3,oneof"`
}

func (*ChangeRequest_Package) isChangeRequest_Request() {}

func (*ChangeRequest_Answer) isChangeRequest_Request() {}

// ChangeEvent is what the host sends on Install and Use.
type ChangeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChangeEvent_Progress
	//	*ChangeEvent_Notice
	//	*ChangeEvent_Done
	//	*ChangeEvent_Prompt
	Event         isChangeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{17}
}

func (x *ChangeEvent) GetEvent() isChangeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChangeEvent) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*ChangeEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ChangeEvent) GetNotice() *Notice {
	if x != nil {
		if x, ok := x.Event.(*ChangeEvent_Notice); ok {
			return x.Notice
		}
	}
	return nil
}

func (x *ChangeEvent) GetDone() *Empty {
	if x != nil {
		if x, ok := x.Event.(*ChangeEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ChangeEvent) GetPrompt() *Prompt {
	if x != nil {
		if x, ok := x.Event.(*ChangeEvent_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

type isChangeEvent_Event interface {
	isChangeEvent_Event()
}

type ChangeEvent_Progress struct {
	Progress *Progress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type ChangeEvent_Notice struct {
	Notice *Notice `protobuf:"bytes,2,opt,name=notice,proto3,oneof"`
}

type ChangeEvent_Done struct {
	// done is sent once the install or use succeeded. The prompts
	// sent until then can still be answered: the host applies the
	// answers and ends the stream when none is left.
	Done *Empty `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

type ChangeEvent_Prompt struct {
	Prompt *Prompt `protobuf:"bytes,4,opt,name=prompt,proto3,oneof"`
}

func (*ChangeEvent_Progress) isChangeEvent_Event() {}

func (*ChangeEvent_Notice) isChangeEvent_Event() {}

func (*ChangeEvent_Done) isChangeEvent_Event() {}

func (*ChangeEvent_Prompt) isChangeEvent_Event() {}

// PackageError is attached to error statuses so the client can restore
// the idepkg sentinel the host's package manager returned.
type PackageError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          PackageError_Kind      `protobuf:"varint,1,opt,name=kind,proto3,enum=pkgrpc.PackageError_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageError) Reset() {
	*x = PackageError{}
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageError) ProtoMessage() {}

func (x *PackageError) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpcpb_pkgrpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageError.ProtoReflect.Descriptor instead.
func (*PackageError) Descriptor() ([]byte, []int) {
	return file_pkgrpcpb_pkgrpc_proto_rawDescGZIP(), []int{18}
}

func (x *PackageError) GetKind() PackageError_Kind {
	if x != nil {
		return x.Kind
	}
	return PackageError_UNKNOWN
}

var File_pkgrpcpb_pkgrpc_proto protoreflect.FileDescriptor

const file_pkgrpcpb_pkgrpc_proto_rawDesc = "" +
	"\n" +
	"\x15pkgrpcpb/pkgrpc.proto\x12\x06pkgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"&\n" +
	"\n" +
	"PackageRef\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\"D\n" +
	"\x0ePackageVersion\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"}\n" +
	"\aFilters\x126\n" +
	"\afilters\x18\x01 \x03(\v2\x1c.pkgrpc.Filters.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\x0ePackageFilters\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12=\n" +
	"\afilters\x18\x02 \x03(\v2#.pkgrpc.PackageFilters.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x14DeleteVersionRequest\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x1d\n" +
	"\x05Paths\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"#\n" +
	"\aVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"8\n" +
	"\x05InUse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x15\n" +
	"\x06in_use\x18\x02 \x01(\bR\x05inUse\"\xfe\x01\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06latest\x18\x02 \x01(\tR\x06latest\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x129\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1d.pkgrpc.Package.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\x06Bundle\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x128\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1c.pkgrpc.Bundle.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\bProgress\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x03R\bprogress\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05units\x18\x03 \x01(\tR\x05units\"L\n" +
	"\x06Notice\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04once\x18\x03 \x01(\bR\x04once\"\x7f\n" +
	"\x06Prompt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\aoptions\x18\x03 \x03(\v2\x14.pkgrpc.PromptOptionR\aoptions\x12\x1b\n" +
	"\tmax_width\x18\x04 \x01(\rR\bmaxWidth\"6\n" +
	"\fPromptOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"<\n" +
	"\x06Answer\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\x04R\x06prompt\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"x\n" +
	"\rChangeRequest\x122\n" +
	"\apackage\x18\x01 \x01(\v2\x16.pkgrpc.PackageVersionH\x00R\apackage\x12(\n" +
	"\x06answer\x18\x02 \x01(\v2\x0e.pkgrpc.AnswerH\x00R\x06answerB\t\n" +
	"\arequest\"\xbf\x01\n" +
	"\vChangeEvent\x12.\n" +
	"\bprogress\x18\x01 \x01(\v2\x10.pkgrpc.ProgressH\x00R\bprogress\x12(\n" +
	"\x06notice\x18\x02 \x01(\v2\x0e.pkgrpc.NoticeH\x00R\x06notice\x12#\n" +
	"\x04done\x18\x03 \x01(\v2\r.pkgrpc.EmptyH\x00R\x04done\x12(\n" +
	"\x06prompt\x18\x04 \x01(\v2\x0e.pkgrpc.PromptH\x00R\x06promptB\a\n" +
	"\x05event\"\xa4\x02\n" +
	"\fPackageError\x12-\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x19.pkgrpc.PackageError.KindR\x04kind\"\xe4\x01\n" +
	"\x04Kind\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rNOT_INSTALLED\x10\x01\x12\x15\n" +
	"\x11PACKAGE_NOT_FOUND\x10\x02\x12\x15\n" +
	"\x11VERSION_NOT_FOUND\x10\x03\x12\x15\n" +
	"\x11ALREADY_INSTALLED\x10\x04\x12\x12\n" +
	"\x0eVERSION_IN_USE\x10\x05\x12\x16\n" +
	"\x12SERVER_UNAVAILABLE\x10\x06\x12\x14\n" +
	"\x10ARTIFACT_MISSING\x10\a\x12\r\n" +
	"\tFORBIDDEN\x10\b\x12\x0f\n" +
	"\vNO_RELEASES\x10\t\x12\x15\n" +
	"\x11NOT_AUTHENTICATED\x10\n" +
	"2\x80\x06\n" +
	"\x0ePackageManager\x12-\n" +
	"\x06LibDir\x12\x12.pkgrpc.PackageRef\x1a\r.pkgrpc.Paths0\x01\x124\n" +
	"\rLatestVersion\x12\x12.pkgrpc.PackageRef\x1a\x0f.pkgrpc.Version\x126\n" +
	"\x0fDescribePackage\x12\x12.pkgrpc.PackageRef\x1a\x0f.pkgrpc.Package\x129\n" +
	"\x0fDescribeRelease\x12\x16.pkgrpc.PackageVersion\x1a\x0e.pkgrpc.Bundle\x122\n" +
	"\fListPackages\x12\x0f.pkgrpc.Filters\x1a\x0f.pkgrpc.Package0\x01\x12?\n" +
	"\x13ListPackageVersions\x12\x16.pkgrpc.PackageFilters\x1a\x0e.pkgrpc.Bundle0\x01\x12<\n" +
	"\x15ListInstalledPackages\x12\r.pkgrpc.Empty\x1a\x12.pkgrpc.PackageRef0\x01\x12E\n" +
	"\x1cListInstalledPackageVersions\x12\x12.pkgrpc.PackageRef\x1a\x0f.pkgrpc.Version0\x01\x129\n" +
	"\aInstall\x12\x15.pkgrpc.ChangeRequest\x1a\x13.pkgrpc.ChangeEvent(\x010\x01\x125\n" +
	"\x03Use\x12\x15.pkgrpc.ChangeRequest\x1a\x13.pkgrpc.ChangeEvent(\x010\x01\x122\n" +
	"\rDeletePackage\x12\x12.pkgrpc.PackageRef\x1a\r.pkgrpc.Empty\x12C\n" +
	"\x14DeletePackageVersion\x12\x1c.pkgrpc.DeleteVersionRequest\x1a\r.pkgrpc.Empty\x121\n" +
	"\fVersionInUse\x12\x12.pkgrpc.PackageRef\x1a\r.pkgrpc.InUseB\vZ\t/pkgrpcpbb\x06proto3"

var (
	file_pkgrpcpb_pkgrpc_proto_rawDescOnce sync.Once
	file_pkgrpcpb_pkgrpc_proto_rawDescData []byte
)

func file_pkgrpcpb_pkgrpc_proto_rawDescGZIP() []byte {
	file_pkgrpcpb_pkgrpc_proto_rawDescOnce.Do(func() {
		file_pkgrpcpb_pkgrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkgrpcpb_pkgrpc_proto_rawDesc), len(file_pkgrpcpb_pkgrpc_proto_rawDesc)))
	})
	return file_pkgrpcpb_pkgrpc_proto_rawDescData
}

var file_pkgrpcpb_pkgrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkgrpcpb_pkgrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkgrpcpb_pkgrpc_proto_goTypes = []any{
	(PackageError_Kind)(0),        // 0: pkgrpc.PackageError.Kind
	(*Empty)(nil),                 // 1: pkgrpc.Empty
	(*PackageRef)(nil),            // 2: pkgrpc.PackageRef
	(*PackageVersion)(nil),        // 3: pkgrpc.PackageVersion
	(*Filters)(nil),               // 4: pkgrpc.Filters
	(*PackageFilters)(nil),        // 5: pkgrpc.PackageFilters
	(*DeleteVersionRequest)(nil),  // 6: pkgrpc.DeleteVersionRequest
	(*Paths)(nil),                 // 7: pkgrpc.Paths
	(*Version)(nil),               // 8: pkgrpc.Version
	(*InUse)(nil),                 // 9: pkgrpc.InUse
	(*Package)(nil),               // 10: pkgrpc.Package
	(*Bundle)(nil),                // 11: pkgrpc.Bundle
	(*Progress)(nil),              // 12: pkgrpc.Progress
	(*Notice)(nil),                // 13: pkgrpc.Notice
	(*Prompt)(nil),                // 14: pkgrpc.Prompt
	(*PromptOption)(nil),          // 15: pkgrpc.PromptOption
	(*Answer)(nil),                // 16: pkgrpc.Answer
	(*ChangeRequest)(nil),         // 17: pkgrpc.ChangeRequest
	(*ChangeEvent)(nil),           // 18: pkgrpc.ChangeEvent
	(*PackageError)(nil),          // 19: pkgrpc.PackageError
	nil,                           // 20: pkgrpc.Filters.FiltersEntry
	nil,                           // 21: pkgrpc.PackageFilters.FiltersEntry
	nil,                           // 22: pkgrpc.Package.MetadataEntry
	nil,                           // 23: pkgrpc.Bundle.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_pkgrpcpb_pkgrpc_proto_depIdxs = []int32{
	20, // 0: pkgrpc.Filters.filters:type_name -> pkgrpc.Filters.FiltersEntry
	21, // 1: pkgrpc.PackageFilters.filters:type_name -> pkgrpc.PackageFilters.FiltersEntry
	22, // 2: pkgrpc.Package.metadata:type_name -> pkgrpc.Package.MetadataEntry
	24, // 3: pkgrpc.Package.created_at:type_name -> google.protobuf.Timestamp
	23, // 4: pkgrpc.Bundle.metadata:type_name -> pkgrpc.Bundle.MetadataEntry
	24, // 5: pkgrpc.Bundle.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: pkgrpc.Prompt.options:type_name -> pkgrpc.PromptOption
	3,  // 7: pkgrpc.ChangeRequest.package:type_name -> pkgrpc.PackageVersion
	16, // 8: pkgrpc.ChangeRequest.answer:type_name -> pkgrpc.Answer
	12, // 9: pkgrpc.ChangeEvent.progress:type_name -> pkgrpc.Progress
	13, // 10: pkgrpc.ChangeEvent.notice:type_name -> pkgrpc.Notice
	1,  // 11: pkgrpc.ChangeEvent.done:type_name -> pkgrpc.Empty
	14, // 12: pkgrpc.ChangeEvent.prompt:type_name -> pkgrpc.Prompt
	0,  // 13: pkgrpc.PackageError.kind:type_name -> pkgrpc.PackageError.Kind
	2,  // 14: pkgrpc.PackageManager.LibDir:input_type -> pkgrpc.PackageRef
	2,  // 15: pkgrpc.PackageManager.LatestVersion:input_type -> pkgrpc.PackageRef
	2,  // 16: pkgrpc.PackageManager.DescribePackage:input_type -> pkgrpc.PackageRef
	3,  // 17: pkgrpc.PackageManager.DescribeRelease:input_type -> pkgrpc.PackageVersion
	4,  // 18: pkgrpc.PackageManager.ListPackages:input_type -> pkgrpc.Filters
	5,  // 19: pkgrpc.PackageManager.ListPackageVersions:input_type -> pkgrpc.PackageFilters
	1,  // 20: pkgrpc.PackageManager.ListInstalledPackages:input_type -> pkgrpc.Empty
	2,  // 21: pkgrpc.PackageManager.ListInstalledPackageVersions:input_type -> pkgrpc.PackageRef
	17, // 22: pkgrpc.PackageManager.Install:input_type -> pkgrpc.ChangeRequest
	17, // 23: pkgrpc.PackageManager.Use:input_type -> pkgrpc.ChangeRequest
	2,  // 24: pkgrpc.PackageManager.DeletePackage:input_type -> pkgrpc.PackageRef
	6,  // 25: pkgrpc.PackageManager.DeletePackageVersion:input_type -> pkgrpc.DeleteVersionRequest
	2,  // 26: pkgrpc.PackageManager.VersionInUse:input_type -> pkgrpc.PackageRef
	7,  // 27: pkgrpc.PackageManager.LibDir:output_type -> pkgrpc.Paths
	8,  // 28: pkgrpc.PackageManager.LatestVersion:output_type -> pkgrpc.Version
	10, // 29: pkgrpc.PackageManager.DescribePackage:output_type -> pkgrpc.Package
	11, // 30: pkgrpc.PackageManager.DescribeRelease:output_type -> pkgrpc.Bundle
	10, // 31: pkgrpc.PackageManager.ListPackages:output_type -> pkgrpc.Package
	11, // 32: pkgrpc.PackageManager.ListPackageVersions:output_type -> pkgrpc.Bundle
	2,  // 33: pkgrpc.PackageManager.ListInstalledPackages:output_type -> pkgrpc.PackageRef
	8,  // 34: pkgrpc.PackageManager.ListInstalledPackageVersions:output_type -> pkgrpc.Version
	18, // 35: pkgrpc.PackageManager.Install:output_type -> pkgrpc.ChangeEvent
	18, // 36: pkgrpc.PackageManager.Use:output_type -> pkgrpc.ChangeEvent
	1,  // 37: pkgrpc.PackageManager.DeletePackage:output_type -> pkgrpc.Empty
	1,  // 38: pkgrpc.PackageManager.DeletePackageVersion:output_type -> pkgrpc.Empty
	9,  // 39: pkgrpc.PackageManager.VersionInUse:output_type -> pkgrpc.InUse
	27, // [27:40] is the sub-list for method output_type
	14, // [14:27] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkgrpcpb_pkgrpc_proto_init() }
func file_pkgrpcpb_pkgrpc_proto_init() {
	if File_pkgrpcpb_pkgrpc_proto != nil {
		return
	}
	file_pkgrpcpb_pkgrpc_proto_msgTypes[16].OneofWrappers = []any{
		(*ChangeRequest_Package)(nil),
		(*ChangeRequest_Answer)(nil),
	}
	file_pkgrpcpb_pkgrpc_proto_msgTypes[17].OneofWrappers = []any{
		(*ChangeEvent_Progress)(nil),
		(*ChangeEvent_Notice)(nil),
		(*ChangeEvent_Done)(nil),
		(*ChangeEvent_Prompt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkgrpcpb_pkgrpc_proto_rawDesc), len(file_pkgrpcpb_pkgrpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkgrpcpb_pkgrpc_proto_goTypes,
		DependencyIndexes: file_pkgrpcpb_pkgrpc_proto_depIdxs,
		EnumInfos:         file_pkgrpcpb_pkgrpc_proto_enumTypes,
		MessageInfos:      file_pkgrpcpb_pkgrpc_proto_msgTypes,
	}.Build()
	File_pkgrpcpb_pkgrpc_proto = out.File
	file_pkgrpcpb_pkgrpc_proto_goTypes = nil
	file_pkgrpcpb_pkgrpc_proto_depIdxs = nil
}
