// Copyright (C) 2017-2026 The Rune Authors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: pkgrpcpb/pkgrpc.proto

package pkgrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PackageManager_LibDir_FullMethodName                       = "/pkgrpc.PackageManager/LibDir"
	PackageManager_LatestVersion_FullMethodName                = "/pkgrpc.PackageManager/LatestVersion"
	PackageManager_DescribePackage_FullMethodName              = "/pkgrpc.PackageManager/DescribePackage"
	PackageManager_DescribeRelease_FullMethodName              = "/pkgrpc.PackageManager/DescribeRelease"
	PackageManager_ListPackages_FullMethodName                 = "/pkgrpc.PackageManager/ListPackages"
	PackageManager_ListPackageVersions_FullMethodName          = "/pkgrpc.PackageManager/ListPackageVersions"
	PackageManager_ListInstalledPackages_FullMethodName        = "/pkgrpc.PackageManager/ListInstalledPackages"
	PackageManager_ListInstalledPackageVersions_FullMethodName = "/pkgrpc.PackageManager/ListInstalledPackageVersions"
	PackageManager_Install_FullMethodName                      = "/pkgrpc.PackageManager/Install"
	PackageManager_Use_FullMethodName                          = "/pkgrpc.PackageManager/Use"
	PackageManager_DeletePackage_FullMethodName                = "/pkgrpc.PackageManager/DeletePackage"
	PackageManager_DeletePackageVersion_FullMethodName         = "/pkgrpc.PackageManager/DeletePackageVersion"
	PackageManager_VersionInUse_FullMethodName                 = "/pkgrpc.PackageManager/VersionInUse"
)

// PackageManagerClient is the client API for PackageManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PackageManager manages the packages of the host serving it. Server
// streams that can fail before producing results send response headers
// once the request is accepted, so a client can tell a rejected request
// from an empty result without waiting for the first message.
//
// Install and Use may change the host's user config. The host asks the
// client's user before replacing any of that user's settings, never
// anyone on the host: the host's own user may not be there to answer.
type PackageManagerClient interface {
	LibDir(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Paths], error)
	LatestVersion(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*Version, error)
	DescribePackage(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*Package, error)
	DescribeRelease(ctx context.Context, in *PackageVersion, opts ...grpc.CallOption) (*Bundle, error)
	ListPackages(ctx context.Context, in *Filters, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Package], error)
	ListPackageVersions(ctx context.Context, in *PackageFilters, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bundle], error)
	ListInstalledPackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageRef], error)
	ListInstalledPackageVersions(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Version], error)
	Install(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeRequest, ChangeEvent], error)
	Use(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeRequest, ChangeEvent], error)
	DeletePackage(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*Empty, error)
	DeletePackageVersion(ctx context.Context, in *DeleteVersionRequest, opts ...grpc.CallOption) (*Empty, error)
	VersionInUse(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*InUse, error)
}

type packageManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPackageManagerClient(cc grpc.ClientConnInterface) PackageManagerClient {
	return &packageManagerClient{cc}
}

func (c *packageManagerClient) LibDir(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Paths], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManager_ServiceDesc.Streams[0], PackageManager_LibDir_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageRef, Paths]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_LibDirClient = grpc.ServerStreamingClient[Paths]

func (c *packageManagerClient) LatestVersion(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*Version, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Version)
	err := c.cc.Invoke(ctx, PackageManager_LatestVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageManagerClient) DescribePackage(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*Package, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Package)
	err := c.cc.Invoke(ctx, PackageManager_DescribePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageManagerClient) DescribeRelease(ctx context.Context, in *PackageVersion, opts ...grpc.CallOption) (*Bundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bundle)
	err := c.cc.Invoke(ctx, PackageManager_DescribeRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageManagerClient) ListPackages(ctx context.Context, in *Filters, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Package], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManager_ServiceDesc.Streams[1], PackageManager_ListPackages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Filters, Package]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListPackagesClient = grpc.ServerStreamingClient[Package]

func (c *packageManagerClient) ListPackageVersions(ctx context.Context, in *PackageFilters, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bundle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManager_ServiceDesc.Streams[2], PackageManager_ListPackageVersions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageFilters, Bundle]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListPackageVersionsClient = grpc.ServerStreamingClient[Bundle]

func (c *packageManagerClient) ListInstalledPackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageRef], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManager_ServiceDesc.Streams[3], PackageManager_ListInstalledPackages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PackageRef]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListInstalledPackagesClient = grpc.ServerStreamingClient[PackageRef]

func (c *packageManagerClient) ListInstalledPackageVersions(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Version], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManager_ServiceDesc.Streams[4], PackageManager_ListInstalledPackageVersions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageRef, Version]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListInstalledPackageVersionsClient = grpc.ServerStreamingClient[Version]

func (c *packageManagerClient) Install(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeRequest, ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManager_ServiceDesc.Streams[5], PackageManager_Install_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeRequest, ChangeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_InstallClient = grpc.BidiStreamingClient[ChangeRequest, ChangeEvent]

func (c *packageManagerClient) Use(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeRequest, ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManager_ServiceDesc.Streams[6], PackageManager_Use_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeRequest, ChangeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_UseClient = grpc.BidiStreamingClient[ChangeRequest, ChangeEvent]

func (c *packageManagerClient) DeletePackage(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PackageManager_DeletePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageManagerClient) DeletePackageVersion(ctx context.Context, in *DeleteVersionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PackageManager_DeletePackageVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageManagerClient) VersionInUse(ctx context.Context, in *PackageRef, opts ...grpc.CallOption) (*InUse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InUse)
	err := c.cc.Invoke(ctx, PackageManager_VersionInUse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackageManagerServer is the server API for PackageManager service.
// All implementations must embed UnimplementedPackageManagerServer
// for forward compatibility.
//
// PackageManager manages the packages of the host serving it. Server
// streams that can fail before producing results send response headers
// once the request is accepted, so a client can tell a rejected request
// from an empty result without waiting for the first message.
//
// Install and Use may change the host's user config. The host asks the
// client's user before replacing any of that user's settings, never
// anyone on the host: the host's own user may not be there to answer.
type PackageManagerServer interface {
	LibDir(*PackageRef, grpc.ServerStreamingServer[Paths]) error
	LatestVersion(context.Context, *PackageRef) (*Version, error)
	DescribePackage(context.Context, *PackageRef) (*Package, error)
	DescribeRelease(context.Context, *PackageVersion) (*Bundle, error)
	ListPackages(*Filters, grpc.ServerStreamingServer[Package]) error
	ListPackageVersions(*PackageFilters, grpc.ServerStreamingServer[Bundle]) error
	ListInstalledPackages(*Empty, grpc.ServerStreamingServer[PackageRef]) error
	ListInstalledPackageVersions(*PackageRef, grpc.ServerStreamingServer[Version]) error
	Install(grpc.BidiStreamingServer[ChangeRequest, ChangeEvent]) error
	Use(grpc.BidiStreamingServer[ChangeRequest, ChangeEvent]) error
	DeletePackage(context.Context, *PackageRef) (*Empty, error)
	DeletePackageVersion(context.Context, *DeleteVersionRequest) (*Empty, error)
	VersionInUse(context.Context, *PackageRef) (*InUse, error)
	mustEmbedUnimplementedPackageManagerServer()
}

// UnimplementedPackageManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackageManagerServer struct{}

func (UnimplementedPackageManagerServer) LibDir(*PackageRef, grpc.ServerStreamingServer[Paths]) error {
	return status.Error(codes.Unimplemented, "method LibDir not implemented")
}
func (UnimplementedPackageManagerServer) LatestVersion(context.Context, *PackageRef) (*Version, error) {
	return nil, status.Error(codes.Unimplemented, "method LatestVersion not implemented")
}
func (UnimplementedPackageManagerServer) DescribePackage(context.Context, *PackageRef) (*Package, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribePackage not implemented")
}
func (UnimplementedPackageManagerServer) DescribeRelease(context.Context, *PackageVersion) (*Bundle, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeRelease not implemented")
}
func (UnimplementedPackageManagerServer) ListPackages(*Filters, grpc.ServerStreamingServer[Package]) error {
	return status.Error(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedPackageManagerServer) ListPackageVersions(*PackageFilters, grpc.ServerStreamingServer[Bundle]) error {
	return status.Error(codes.Unimplemented, "method ListPackageVersions not implemented")
}
func (UnimplementedPackageManagerServer) ListInstalledPackages(*Empty, grpc.ServerStreamingServer[PackageRef]) error {
	return status.Error(codes.Unimplemented, "method ListInstalledPackages not implemented")
}
func (UnimplementedPackageManagerServer) ListInstalledPackageVersions(*PackageRef, grpc.ServerStreamingServer[Version]) error {
	return status.Error(codes.Unimplemented, "method ListInstalledPackageVersions not implemented")
}
func (UnimplementedPackageManagerServer) Install(grpc.BidiStreamingServer[ChangeRequest, ChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedPackageManagerServer) Use(grpc.BidiStreamingServer[ChangeRequest, ChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method Use not implemented")
}
func (UnimplementedPackageManagerServer) DeletePackage(context.Context, *PackageRef) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePackage not implemented")
}
func (UnimplementedPackageManagerServer) DeletePackageVersion(context.Context, *DeleteVersionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePackageVersion not implemented")
}
func (UnimplementedPackageManagerServer) VersionInUse(context.Context, *PackageRef) (*InUse, error) {
	return nil, status.Error(codes.Unimplemented, "method VersionInUse not implemented")
}
func (UnimplementedPackageManagerServer) mustEmbedUnimplementedPackageManagerServer() {}
func (UnimplementedPackageManagerServer) testEmbeddedByValue()                        {}

// UnsafePackageManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackageManagerServer will
// result in compilation errors.
type UnsafePackageManagerServer interface {
	mustEmbedUnimplementedPackageManagerServer()
}

func RegisterPackageManagerServer(s grpc.ServiceRegistrar, srv PackageManagerServer) {
	// If the following call panics, it indicates UnimplementedPackageManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackageManager_ServiceDesc, srv)
}

func _PackageManager_LibDir_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageManagerServer).LibDir(m, &grpc.GenericServerStream[PackageRef, Paths]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_LibDirServer = grpc.ServerStreamingServer[Paths]

func _PackageManager_LatestVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServer).LatestVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManager_LatestVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServer).LatestVersion(ctx, req.(*PackageRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageManager_DescribePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServer).DescribePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManager_DescribePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServer).DescribePackage(ctx, req.(*PackageRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageManager_DescribeRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServer).DescribeRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManager_DescribeRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServer).DescribeRelease(ctx, req.(*PackageVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageManager_ListPackages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filters)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageManagerServer).ListPackages(m, &grpc.GenericServerStream[Filters, Package]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListPackagesServer = grpc.ServerStreamingServer[Package]

func _PackageManager_ListPackageVersions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageFilters)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageManagerServer).ListPackageVersions(m, &grpc.GenericServerStream[PackageFilters, Bundle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListPackageVersionsServer = grpc.ServerStreamingServer[Bundle]

func _PackageManager_ListInstalledPackages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageManagerServer).ListInstalledPackages(m, &grpc.GenericServerStream[Empty, PackageRef]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListInstalledPackagesServer = grpc.ServerStreamingServer[PackageRef]

func _PackageManager_ListInstalledPackageVersions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageManagerServer).ListInstalledPackageVersions(m, &grpc.GenericServerStream[PackageRef, Version]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_ListInstalledPackageVersionsServer = grpc.ServerStreamingServer[Version]

func _PackageManager_Install_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PackageManagerServer).Install(&grpc.GenericServerStream[ChangeRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_InstallServer = grpc.BidiStreamingServer[ChangeRequest, ChangeEvent]

func _PackageManager_Use_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PackageManagerServer).Use(&grpc.GenericServerStream[ChangeRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManager_UseServer = grpc.BidiStreamingServer[ChangeRequest, ChangeEvent]

func _PackageManager_DeletePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServer).DeletePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManager_DeletePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServer).DeletePackage(ctx, req.(*PackageRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageManager_DeletePackageVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServer).DeletePackageVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManager_DeletePackageVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServer).DeletePackageVersion(ctx, req.(*DeleteVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageManager_VersionInUse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServer).VersionInUse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManager_VersionInUse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServer).VersionInUse(ctx, req.(*PackageRef))
	}
	return interceptor(ctx, in, info, handler)
}

// PackageManager_ServiceDesc is the grpc.ServiceDesc for PackageManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackageManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkgrpc.PackageManager",
	HandlerType: (*PackageManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LatestVersion",
			Handler:    _PackageManager_LatestVersion_Handler,
		},
		{
			MethodName: "DescribePackage",
			Handler:    _PackageManager_DescribePackage_Handler,
		},
		{
			MethodName: "DescribeRelease",
			Handler:    _PackageManager_DescribeRelease_Handler,
		},
		{
			MethodName: "DeletePackage",
			Handler:    _PackageManager_DeletePackage_Handler,
		},
		{
			MethodName: "DeletePackageVersion",
			Handler:    _PackageManager_DeletePackageVersion_Handler,
		},
		{
			MethodName: "VersionInUse",
			Handler:    _PackageManager_VersionInUse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LibDir",
			Handler:       _PackageManager_LibDir_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListPackages",
			Handler:       _PackageManager_ListPackages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListPackageVersions",
			Handler:       _PackageManager_ListPackageVersions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListInstalledPackages",
			Handler:       _PackageManager_ListInstalledPackages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListInstalledPackageVersions",
			Handler:       _PackageManager_ListInstalledPackageVersions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Install",
			Handler:       _PackageManager_Install_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Use",
			Handler:       _PackageManager_Use_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkgrpcpb/pkgrpc.proto",
}
